import type { EffectSpec } from "../../engine/effectSpec";
import { mainAndAction } from "../standardSpecs";
import { TOKEN_ALVAARON, TOKEN_PARTS, TOKEN_WIRE_GUIDED_ARM, TOKEN_ZEONG_HEAD } from "./tokens";

/**
 * Wave W3 (GD04-A) — cláusulas do GD04 que o vocabulário atual (até a W2c) já cobre: tokens,
 * gatilhos de Deploy/Attack/Destroyed/When Paired/When Linked, Commands e o resto das Bases.
 */

const target = { kind: "named", name: "target" } as const;
const self = { kind: "self" } as const;
const shield = { op: "addShieldToHand", player: "controller", count: 1 } as const;

export const GD04_W3_EFFECT_SPECS: EffectSpec[] = [
  // ——— Units ———
  {
    id: "GD04-003-Attack",
    cardCode: "GD04-003",
    trigger: "Attack",
    condition: { predicate: "controllerUnitCountWithAnyTraitAtLeast:League Militaire:3", then: [{ op: "draw", player: "controller", n: 1 }] },
    actions: [],
    sourceText: "【Attack】If you have 3 or more (League Militaire) Units in play, draw 1.",
  },
  {
    id: "GD04-007-Attack",
    cardCode: "GD04-007",
    trigger: "Attack",
    duringPair: true,
    actions: [{ op: "spawnToken", def: TOKEN_PARTS, player: "controller", zone: "battleArea" }],
    sourceText: "【During Pair】【Attack】Deploy 1 [Parts]((League Militaire)･AP1･HP1･This Unit can't choose the enemy player as its attack target) Unit token.",
  },
  {
    id: "GD04-009-WhenLinked",
    cardCode: "GD04-009",
    trigger: "When Linked",
    actions: [{ op: "setActive", target }],
    targetScope: "friendlyUnit",
    targetFilter: "trait:White Base Team;level>=4;notSelf",
    sourceText: "【When Linked】Choose 1 of your other (White Base Team) Units that is Lv.4 or higher. Set it as active.",
  },
  {
    id: "GD04-011-Destroyed",
    cardCode: "GD04-011",
    trigger: "Destroyed",
    condition: {
      predicate: "controllerOtherUnitWithTrait:League Militaire",
      then: [{ op: "spawnToken", def: TOKEN_PARTS, player: "controller", zone: "battleArea" }],
    },
    actions: [],
    sourceText: "【Destroyed】If another friendly (League Militaire) Unit is in play, deploy 1 [Parts]((League Militaire)･AP1･HP1･This Unit can't choose the enemy player as its attack target) Unit token.",
  },
  {
    id: "GD04-015-Deploy",
    cardCode: "GD04-015",
    trigger: "Deploy",
    actions: [
      { op: "rest", target },
      { op: "rest", target: { kind: "named", name: "enemyTarget" } },
    ],
    targetScope: "friendlyUnit",
    targetFilter: "trait:League Militaire;active",
    secondaryTarget: { name: "enemyTarget", targetScope: "enemyUnit", targetFilter: "level<=3" },
    sourceText: "【Deploy】Choose 1 of your active (League Militaire) Units and 1 enemy Unit that is Lv.3 or lower. Rest them.",
  },
  {
    id: "GD04-017-WhenPaired",
    cardCode: "GD04-017",
    trigger: "When Paired",
    condition: {
      predicate: "pairedPilotHasTrait:Newtype",
      then: [{ op: "spawnToken", def: TOKEN_WIRE_GUIDED_ARM, player: "controller", zone: "battleArea", count: 2 }],
    },
    actions: [],
    sourceText: "【When Paired･(Newtype) Pilot】Deploy 2 [Wire-Guided Arm]((Zeon)･AP2･HP1･This Unit can't be paired with a Pilot) Unit tokens.",
  },
  {
    id: "GD04-017-Destroyed",
    cardCode: "GD04-017",
    trigger: "Destroyed",
    actions: [{ op: "spawnToken", def: TOKEN_ZEONG_HEAD, player: "controller", zone: "battleArea", rested: true }],
    sourceText: "【Destroyed】Deploy 1 rested [Zeong (Head)]((Zeon)･AP3･HP1) Unit token.",
  },
  {
    id: "GD04-019-Destroyed",
    cardCode: "GD04-019",
    trigger: "Destroyed",
    actions: [{ op: "lookAtTopFilterReveal", player: "controller", count: 3, filter: { cardType: "UNIT", anyTrait: ["CB"], maxLevel: 5 } }],
    sourceText: "【Destroyed】Look at the top 3 cards of your deck. You may reveal 1 (CB) Unit card that is Lv.5 or lower among them and add it to your hand. Return the remaining cards randomly to the bottom of your deck.",
  },
  {
    id: "GD04-024-Deploy",
    cardCode: "GD04-024",
    trigger: "Deploy",
    actions: [{ op: "lookAtTopFilterReveal", player: "controller", count: 3, filter: { anyCardType: ["UNIT", "COMMAND"], anyTrait: ["Academy"] } }],
    sourceText: "【Deploy】Look at the top 3 cards of your deck. You may reveal 1 (Academy) Unit card/Command card among them and add it to your hand. Return the remaining cards randomly to the bottom of your deck.",
  },
  {
    id: "GD04-028-Attack",
    cardCode: "GD04-028",
    trigger: "Attack",
    actions: [{ op: "grantKeyword", target, keyword: "Blocker", duration: "endOfTurn" }],
    targetScope: "enemyUnit",
    targetFilter: "active",
    sourceText: "【Attack】Choose 1 active enemy Unit. It gains <Blocker> during this turn.",
  },
  {
    id: "GD04-038-Deploy",
    cardCode: "GD04-038",
    trigger: "Deploy",
    condition: { predicate: "enemyUnitCountAtLeast:2", then: [{ op: "damageUnit", target, amount: 2 }] },
    actions: [],
    targetScope: "enemyUnit",
    targetFilter: "level<=2",
    sourceText: "【Deploy】If 2 or more enemy Units are in play, choose 1 enemy Unit that is Lv.2 or lower. Deal 2 damage to it.",
  },
  {
    id: "GD04-046-Deploy",
    cardCode: "GD04-046",
    trigger: "Deploy",
    optional: true,
    condition: { predicate: "selfIsActive", then: [{ op: "rest", target: self }, { op: "damageUnit", target, amount: 2 }] },
    actions: [],
    targetScope: "enemyUnit",
    targetFilter: "level<=3",
    sourceText: "【Deploy】You may rest this Unit. If you do, choose 1 enemy Unit that is Lv.3 or lower. Deal 2 damage to it.",
  },
  {
    id: "GD04-052-Attack",
    cardCode: "GD04-052",
    trigger: "Attack",
    duringPair: true,
    optional: true,
    actions: [
      { op: "damageUnit", target, amount: 2 },
      { op: "damageUnit", target: self, amount: 2 },
    ],
    targetScope: "enemyUnit",
    sourceText: "【During Pair】【Attack】You may choose 1 enemy Unit. Deal 2 damage to it and this Unit.",
  },
  {
    id: "GD04-054-BattleDamage",
    cardCode: "GD04-054",
    trigger: "Reaction:battleDamageToEnemyUnit",
    reaction: { event: "battleDamageToEnemyUnit", subject: "self" },
    condition: { predicate: "battleVictimInPlay", then: [{ op: "destroy", target: { kind: "named", name: "battleVictim" } }] },
    actions: [],
    sourceText: "When this Unit deals battle damage to an enemy Unit, destroy that enemy Unit.",
  },
  {
    id: "GD04-056-Deploy",
    cardCode: "GD04-056",
    trigger: "Deploy",
    actions: [
      { op: "damageUnit", target: self, amount: 1 },
      { op: "rest", target },
    ],
    targetScope: "enemyUnit",
    targetFilter: "ap<=3",
    sourceText: "【Deploy】Deal 1 damage to this Unit. If you do, choose 1 enemy Unit with 3 or less AP. Rest it.",
  },
  {
    id: "GD04-065-Attack",
    cardCode: "GD04-065",
    trigger: "Attack",
    actions: [{ op: "modifyStat", target: { kind: "group", group: { kind: "allEnemyUnits" } }, stat: "ap", amount: -1, duration: "endOfTurn" }],
    sourceText: "【Attack】All enemy Units get AP-1 during this turn.",
  },
  {
    id: "GD04-072-WhenLinked",
    cardCode: "GD04-072",
    trigger: "When Linked",
    actions: [{ op: "moveZone", target, toZone: "hand" }],
    targetScope: "enemyUnit",
    targetFilter: "hp<=3",
    sourceText: "【When Linked】Choose 1 enemy Unit with 3 or less HP. Return it to its owner's hand.",
  },
  {
    id: "GD04-073-ActivateMain",
    cardCode: "GD04-073",
    trigger: "Activate·Main",
    oncePerTurn: true,
    cost: [{ op: "payResourceCost", player: "controller", n: 1 }],
    actions: [{ op: "modifyStat", target: self, stat: "ap", amount: 2, duration: "endOfTurn" }],
    sourceText: "【Activate･Main】【Once per Turn】①：This Unit gets AP+2 during this turn.",
  },
  {
    id: "GD04-080-Destroyed",
    cardCode: "GD04-080",
    trigger: "Destroyed",
    condition: {
      predicate: "controllerOtherUnitCountWithAnyTraitAtLeast:UN,Superpower Bloc:1",
      then: [{ op: "spawnToken", def: TOKEN_ALVAARON, player: "controller", zone: "battleArea", rested: true }],
    },
    actions: [],
    sourceText: "【Destroyed】If you have another (UN)/(Superpower Bloc) Unit in play, deploy 1 rested [Alvaaron]((UN)･AP4･HP1) Unit token.",
  },
  // ——— Pilots ———
  {
    id: "GD04-081-WhenPaired",
    cardCode: "GD04-081",
    trigger: "When Paired",
    condition: {
      predicate: "selfHasTrait:League Militaire",
      then: [{ op: "spawnToken", def: TOKEN_PARTS, player: "controller", zone: "battleArea" }],
    },
    actions: [],
    sourceText: "【When Paired】If this is a (League Militaire) Unit, deploy 1 [Parts]((League Militaire)･AP1･HP1･This Unit can't choose the enemy player as its attack target) Unit token.",
  },
  {
    id: "GD04-082-WhenLinked",
    cardCode: "GD04-082",
    trigger: "When Linked",
    actions: [{ op: "damageUnit", target, amount: 1 }],
    targetScope: "anyUnit",
    targetFilter: "rested",
    sourceText: "【When Linked】Choose 1 rested Unit. Deal 1 damage to it.",
  },
  {
    id: "GD04-084-Attack",
    cardCode: "GD04-084",
    trigger: "Attack",
    actions: [{ op: "modifyStat", target, stat: "ap", amount: 1, duration: "endOfTurn" }],
    targetScope: "friendlyUnit",
    targetFilter: "trait:White Base Team",
    sourceText: "【Attack】Choose 1 of your (White Base Team) Units. It gets AP+1 during this turn.",
  },
  {
    id: "GD04-092-WhenLinked",
    cardCode: "GD04-092",
    trigger: "When Linked",
    actions: [{ op: "damageUnit", target, amount: 1 }],
    targetScope: "enemyUnit",
    targetFilter: "damaged",
    sourceText: "【When Linked】Choose 1 damaged enemy Unit. Deal 1 damage to it.",
  },
  {
    id: "GD04-097-WhenLinked",
    cardCode: "GD04-097",
    trigger: "When Linked",
    actions: [{ op: "moveZone", target, toZone: "hand" }],
    targetScope: "enemyUnit",
    targetFilter: "hp<=3",
    sourceText: "【When Linked】Choose 1 enemy Unit with 3 or less HP. Return it to its owner's hand.",
  },
  // ——— Commands ———
  {
    id: "GD04-102-Burst",
    cardCode: "GD04-102",
    trigger: "Burst",
    actions: [{ op: "draw", player: "controller", n: 1 }],
    sourceText: "【Burst】Draw 1.",
  },
  {
    id: "GD04-103-Main",
    cardCode: "GD04-103",
    trigger: "Main",
    actions: [{ op: "grantKeyword", target, keyword: "Repair 2", duration: "endOfTurn" }],
    targetScope: "friendlyUnit",
    sourceText: "【Main】Choose 1 of your Units. It gains <Repair 2> during this turn.",
  },
  ...mainAndAction({
    cardCode: "GD04-104",
    actions: [{ op: "rest", target: { kind: "namedGroup", name: "target" } }],
    targetScope: "enemyUnit",
    targetFilter: "level<=2",
    targetCount: { min: 1, max: 2 },
    sourceText: "【Main】/【Action】Choose 1 to 2 enemy Units that are Lv.2 or lower. Rest them.",
  }),
  {
    id: "GD04-105-Main",
    cardCode: "GD04-105",
    trigger: "Main",
    actions: [{ op: "lookAtTopFilterReveal", player: "controller", count: 5, filter: { cardType: "PILOT" } }],
    sourceText: "【Main】Look at the top 5 cards of your deck. You may reveal 1 Pilot card among them and add it to your hand. Return the remaining cards randomly to the bottom of your deck.",
  },
  ...mainAndAction({
    cardCode: "GD04-109",
    actions: [{ op: "damageUnit", target, amount: 4 }],
    targetScope: "enemyUnit",
    targetFilter: "level<=6",
    sourceText: "【Main】/【Action】Choose 1 enemy Unit that is Lv.6 or lower. Deal 4 damage to it.",
  }),
  ...mainAndAction({
    cardCode: "GD04-111",
    actions: [{ op: "modifyStat", target: { kind: "namedGroup", name: "target" }, stat: "ap", amount: 2, duration: "endOfTurn" }],
    targetScope: "friendlyUnit",
    targetFilter: "trait:CB",
    targetCount: { min: 1, max: 3 },
    sourceText: "【Main】/【Action】Choose 1 to 3 of your (CB) Units. They get AP+2 during this turn.",
  }),
  {
    id: "GD04-112-Main",
    cardCode: "GD04-112",
    trigger: "Main",
    actions: [{ op: "damageUnit", target: { kind: "group", group: { kind: "allUnits", maxLevel: 2 } }, amount: 1 }],
    sourceText: "【Main】Deal 1 damage to all Units that are Lv.2 or lower.",
  },
  {
    id: "GD04-113-Burst",
    cardCode: "GD04-113",
    trigger: "Burst",
    actions: [{ op: "modifyStat", target, stat: "ap", amount: -2, duration: "endOfTurn" }],
    targetScope: "enemyUnit",
    sourceText: "【Burst】Choose 1 enemy Unit. It gets AP-2 during this turn.",
  },
  {
    id: "GD04-114-Burst",
    cardCode: "GD04-114",
    trigger: "Burst",
    actions: [{ op: "searchTrashToHand", player: "controller", filter: { cardType: "UNIT", nameContains: "Trans-Am" } }],
    sourceText: "【Burst】Choose 1 Unit card with \"Trans-Am\" in its card name from your trash. Add it to your hand.",
  },
  ...mainAndAction({
    cardCode: "GD04-114",
    actions: [
      { op: "damageUnit", target, amount: 1 },
      { op: "damageUnit", target: { kind: "named", name: "enemyTarget" }, amount: 1 },
    ],
    targetScope: "friendlyUnit",
    secondaryTarget: { name: "enemyTarget", targetScope: "enemyUnit" },
    sourceText: "【Main】/【Action】Choose 1 of your Units and 1 enemy Unit. Deal 1 damage to them.",
  }),
  {
    id: "GD04-115-Burst",
    cardCode: "GD04-115",
    trigger: "Burst",
    actions: [{ op: "damageUnit", target, amount: 1 }],
    targetScope: "enemyUnit",
    sourceText: "【Burst】Choose 1 enemy Unit. Deal 1 damage to it.",
  },
  {
    id: "GD04-117-Burst",
    cardCode: "GD04-117",
    trigger: "Burst",
    actions: [{ op: "moveZone", target: { kind: "namedGroup", name: "target" }, toZone: "hand" }],
    targetScope: "enemyUnit",
    targetFilter: "level<=3",
    targetCount: { min: 1, max: 2 },
    sourceText: "【Burst】Activate this card's 【Action】.",
  },
  {
    id: "GD04-117-Action",
    cardCode: "GD04-117",
    trigger: "Action",
    actions: [{ op: "moveZone", target: { kind: "namedGroup", name: "target" }, toZone: "hand" }],
    targetScope: "enemyUnit",
    targetFilter: "level<=3",
    targetCount: { min: 1, max: 2 },
    sourceText: "【Action】Choose 1 to 2 enemy Units that are Lv.3 or lower. Return them to their owners' hands.",
  },
  ...mainAndAction({
    cardCode: "GD04-118",
    condition: { predicate: "controllerUnitCountWithAnyTraitAtLeast:UN:2", then: [{ op: "moveZone", target, toZone: "hand" }] },
    actions: [],
    targetScope: "enemyUnit",
    targetFilter: "hp<=5",
    sourceText: "【Main】/【Action】If 2 or more friendly (UN) Units are in play, choose 1 enemy Unit with 5 or less HP. Return it to its owner's hand.",
  }),
  ...mainAndAction({
    cardCode: "GD04-120",
    actions: [{ op: "modifyStat", target, stat: "ap", amount: 2, duration: "endOfTurn" }],
    targetScope: "friendlyUnit",
    targetFilter: "anyTrait:Militia,Dianna Counter",
    sourceText: "【Main】/【Action】Choose 1 friendly (Militia)/(Dianna Counter) Unit. It gets AP+2 during this turn.",
  }),
  // ——— Bases ———
  {
    id: "GD04-121-Deploy",
    cardCode: "GD04-121",
    trigger: "Deploy",
    condition: {
      predicate: "isControllersTurn;controllerUnitWithTraitInPlay:League Militaire",
      then: [{ op: "spawnToken", def: TOKEN_PARTS, player: "controller", zone: "battleArea" }],
    },
    actions: [shield],
    sourceText: "【Deploy】Add 1 of your Shields to your hand. Then, during your turn, if a friendly (League Militaire) Unit is in play, deploy 1 [Parts]((League Militaire)･AP1･HP1･This Unit can't choose the enemy player as its attack target) Unit token.",
  },
  {
    id: "GD04-127-Deploy",
    cardCode: "GD04-127",
    trigger: "Deploy",
    condition: { predicate: "controllerTrashCardCountWithAnyTraitAtLeast:Vulture:7", then: [{ op: "destroy", target }] },
    actions: [shield],
    targetScope: "enemyUnit",
    targetFilter: "ap<=2",
    sourceText: "【Deploy】Add 1 of your Shields to your hand. Then, if there are 7 or more (Vulture) cards in your trash, choose 1 enemy Unit with 2 or less AP. Destroy it.",
  },
  {
    id: "GD04-128-Destroyed",
    cardCode: "GD04-128",
    trigger: "Destroyed",
    actions: [
      { op: "draw", player: "controller", n: 1 },
      { op: "draw", player: "opponent", n: 1 },
    ],
    sourceText: "【Destroyed】All players draw 1.",
  },
  {
    id: "GD04-129-Deploy",
    cardCode: "GD04-129",
    trigger: "Deploy",
    actions: [shield, { op: "damageUnit", target: self, amount: 3 }],
    sourceText: "【Deploy】Add 1 of your Shields to your hand. Then, deal 3 damage to this Base.",
  },
  {
    id: "GD04-130-ActivateMain",
    cardCode: "GD04-130",
    trigger: "Activate·Main",
    oncePerTurn: true,
    cost: [{ op: "moveZone", target: { kind: "group", group: { kind: "firstNInTrash", count: 1, filter: { cardType: "COMMAND" } } }, toZone: "exile" }],
    actions: [{ op: "modifyStat", target, stat: "ap", amount: -1, duration: "endOfTurn" }],
    targetScope: "enemyUnit",
    sourceText: "【Activate･Main】【Once per Turn】Exile 1 Command card from your trash：Choose 1 enemy Unit. It gets AP-1 during this turn.",
  },
];
