import type { CardDef } from "../../engine/types";

export const BASES: Record<string, CardDef> = {
  "GD02-121": {
    code: "GD02-121",
    nameEn: "Dominion",
    cardType: "BASE",
    color: "blue",
    level: 4,
    cost: 1,
    ap: 0,
    hp: 5,
    traits: ["Earth Alliance","Warship"],
    triggerKeywords: ["Burst","Deploy"],
    hasBurst: true,
  },
  "GD02-122": {
    code: "GD02-122",
    nameEn: "Alexandria",
    cardType: "BASE",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 0,
    hp: 5,
    traits: ["Titans","Warship"],
    triggerKeywords: ["Burst","Deploy"],
    hasBurst: true,
  },
  "GD02-123": {
    code: "GD02-123",
    nameEn: "Sodon",
    cardType: "BASE",
    color: "green",
    level: 3,
    cost: 2,
    ap: 0,
    hp: 5,
    traits: ["Zeon","Warship"],
    triggerKeywords: ["Burst","Deploy"],
    hasBurst: true,
  },
  "GD02-124": {
    code: "GD02-124",
    nameEn: "Diva",
    cardType: "BASE",
    color: "green",
    level: 3,
    cost: 1,
    ap: 0,
    hp: 5,
    traits: ["Earth Federation","Warship"],
    triggerKeywords: ["Burst","Deploy"],
    hasBurst: true,
  },
  "GD02-125": {
    code: "GD02-125",
    nameEn: "Gwadan",
    cardType: "BASE",
    color: "red",
    level: 4,
    cost: 2,
    ap: 0,
    hp: 5,
    traits: ["Neo Zeon","Warship"],
    triggerKeywords: ["Burst","Deploy"],
    hasBurst: true,
  },
  "GD02-126": {
    code: "GD02-126",
    nameEn: "Shuji's Hideout",
    cardType: "BASE",
    color: "red",
    level: 3,
    cost: 1,
    ap: 0,
    hp: 5,
    traits: ["Clan","Stronghold"],
    triggerKeywords: ["Burst","Deploy","Destroyed"],
    hasBurst: true,
  },
  "GD02-127": {
    code: "GD02-127",
    nameEn: "Freeden",
    cardType: "BASE",
    color: "purple",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 5,
    traits: ["Vulture","Warship"],
    triggerKeywords: ["Burst","Deploy","Destroyed"],
    hasBurst: true,
  },
  "GD02-128": {
    code: "GD02-128",
    nameEn: "Hammerhead",
    cardType: "BASE",
    color: "purple",
    level: 4,
    cost: 2,
    ap: 0,
    hp: 5,
    traits: ["Teiwaz","Warship"],
    triggerKeywords: ["Burst","Deploy"],
    hasBurst: true,
  },
  "GD02-129": {
    code: "GD02-129",
    nameEn: "Argama",
    cardType: "BASE",
    color: "white",
    level: 3,
    cost: 1,
    ap: 0,
    hp: 5,
    traits: ["AEUG","Warship"],
    triggerKeywords: ["Burst","Deploy"],
    hasBurst: true,
  },
  "GD02-130": {
    code: "GD02-130",
    nameEn: "Sleipnir",
    cardType: "BASE",
    color: "white",
    level: 4,
    cost: 2,
    ap: 0,
    hp: 5,
    traits: ["Gjallarhorn","Warship"],
    triggerKeywords: ["Burst","Deploy"],
    hasBurst: true,
  },
};
