import type { CardDef } from "../../engine/types";

export const COMMANDS: Record<string, CardDef> = {
  "GD02-100": {
    code: "GD02-100",
    nameEn: "Dramatic Turnabout",
    cardType: "COMMAND",
    color: "blue",
    level: 5,
    cost: 2,
    triggerKeywords: ["Burst","Main"],
    hasBurst: true,
  },
  "GD02-101": {
    code: "GD02-101",
    nameEn: "Beneath the Mask",
    cardType: "COMMAND",
    color: "blue",
    level: 1,
    cost: 1,
    triggerKeywords: ["Main","Action"],
  },
  "GD02-102": {
    code: "GD02-102",
    nameEn: "Mouar's Determination",
    cardType: "COMMAND",
    color: "blue",
    level: 2,
    cost: 1,
    ap: 1,
    hp: 0,
    traits: ["Titans"],
    triggerKeywords: ["Main","Action"],
    pilotMode: {"pilotName":"Mouar Pharaoh","ap":1,"hp":0},
  },
  "GD02-103": {
    code: "GD02-103",
    nameEn: "AGE Device",
    cardType: "COMMAND",
    color: "green",
    level: 4,
    cost: 2,
    triggerKeywords: ["Burst","Main"],
    hasBurst: true,
  },
  "GD02-104": {
    code: "GD02-104",
    nameEn: "Turning Point of History",
    cardType: "COMMAND",
    color: "green",
    level: 1,
    cost: 1,
    triggerKeywords: ["Main"],
  },
  "GD02-105": {
    code: "GD02-105",
    nameEn: "Valedictorian",
    cardType: "COMMAND",
    color: "green",
    level: 2,
    cost: 1,
    ap: 1,
    hp: 0,
    triggerKeywords: ["Action"],
    pilotMode: {"pilotName":"Xavier Olivette","ap":1,"hp":0},
  },
  "GD02-107": {
    code: "GD02-107",
    nameEn: "All-Range Attack",
    cardType: "COMMAND",
    color: "red",
    level: 4,
    cost: 2,
    triggerKeywords: ["Burst","Main"],
    hasBurst: true,
  },
  "GD02-108": {
    code: "GD02-108",
    nameEn: "That One Looks A Lot Stronger?",
    cardType: "COMMAND",
    color: "red",
    level: 3,
    cost: 1,
    triggerKeywords: ["Main"],
  },
  "GD02-109": {
    code: "GD02-109",
    nameEn: "Undying Persistence",
    cardType: "COMMAND",
    color: "red",
    level: 4,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Clan","Newtype"],
    triggerKeywords: ["Main","Action"],
    pilotMode: {"pilotName":"Shiiko Sugai","ap":1,"hp":1},
  },
  "GD02-110": {
    code: "GD02-110",
    nameEn: "Awakened Power",
    cardType: "COMMAND",
    color: "purple",
    level: 6,
    cost: 2,
    triggerKeywords: ["Main"],
  },
  "GD02-111": {
    code: "GD02-111",
    nameEn: "Decisive Last Resort",
    cardType: "COMMAND",
    color: "purple",
    level: 5,
    cost: 4,
    triggerKeywords: ["Burst","Main"],
    hasBurst: true,
  },
  "GD02-112": {
    code: "GD02-112",
    nameEn: "Momentary Respite",
    cardType: "COMMAND",
    color: "purple",
    level: 4,
    cost: 3,
    triggerKeywords: ["Burst","Main"],
    hasBurst: true,
  },
  "GD02-113": {
    code: "GD02-113",
    nameEn: "Sisterly Care",
    cardType: "COMMAND",
    color: "purple",
    level: 4,
    cost: 2,
    ap: 1,
    hp: 1,
    traits: ["Teiwaz"],
    triggerKeywords: ["Main","Action"],
    pilotMode: {"pilotName":"Amida Arca","ap":1,"hp":1},
  },
  "GD02-114": {
    code: "GD02-114",
    nameEn: "It's Name is Ryusei-Go",
    cardType: "COMMAND",
    color: "purple",
    level: 2,
    cost: 1,
    ap: 1,
    hp: 0,
    traits: ["Tekkadan","Alaya-Vijnana"],
    triggerKeywords: ["Main","Action"],
    pilotMode: {"pilotName":"Norba Shino","ap":1,"hp":0},
  },
  "GD02-115": {
    code: "GD02-115",
    nameEn: "Familial Devotion",
    cardType: "COMMAND",
    color: "purple",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 1,
    traits: ["Vulture"],
    triggerKeywords: ["Main","Action"],
    pilotMode: {"pilotName":"Witz Sou","ap":0,"hp":1},
  },
  "GD02-116": {
    code: "GD02-116",
    nameEn: "Comrades Come First",
    cardType: "COMMAND",
    color: "purple",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 0,
    traits: ["Vulture"],
    triggerKeywords: ["Main"],
    pilotMode: {"pilotName":"Roybea Loy","ap":1,"hp":0},
  },
  "GD02-117": {
    code: "GD02-117",
    nameEn: "A New Sign",
    cardType: "COMMAND",
    color: "white",
    level: 4,
    cost: 3,
    triggerKeywords: ["Burst","Main"],
    hasBurst: true,
  },
  "GD02-118": {
    code: "GD02-118",
    nameEn: "Heart Set on Revenge",
    cardType: "COMMAND",
    color: "white",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 0,
    traits: ["Gjallarhorn"],
    triggerKeywords: ["Action"],
    pilotMode: {"pilotName":"Ein Dalton","ap":1,"hp":0},
  },
  "GD02-119": {
    code: "GD02-119",
    nameEn: "Persistent and Fortudinous",
    cardType: "COMMAND",
    color: "white",
    level: 2,
    cost: 1,
    ap: 1,
    hp: 0,
    traits: ["Gjallarhorn"],
    triggerKeywords: ["Action"],
    pilotMode: {"pilotName":"Carta Issue","ap":1,"hp":0},
  },
  "GD02-120": {
    code: "GD02-120",
    nameEn: "Aspiring Pilot",
    cardType: "COMMAND",
    color: "white",
    level: 3,
    cost: 1,
    ap: 0,
    hp: 1,
    traits: ["AEUG"],
    triggerKeywords: ["Action"],
    pilotMode: {"pilotName":"Fa Yuiry","ap":0,"hp":1},
  },
};
