import type { CardDef } from "../../engine/types";

export const PILOTS: Record<string, CardDef> = {
  "GD02-085": {
    code: "GD02-085",
    nameEn: "Four Murasame",
    cardType: "PILOT",
    color: "blue",
    level: 5,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Titans","Cyber-Newtype"],
    triggerKeywords: ["Burst","During Link"],
    hasBurst: true,
  },
  "GD02-086": {
    code: "GD02-086",
    nameEn: "Jerid Messa",
    cardType: "PILOT",
    color: "blue",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Titans"],
    triggerKeywords: ["Burst"],
    hasBurst: true,
  },
  "GD02-087": {
    code: "GD02-087",
    nameEn: "Orga, Crot, and Shani",
    cardType: "PILOT",
    color: "blue",
    level: 5,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Earth Alliance","Biological CPU"],
    triggerKeywords: ["Burst","When Linked"],
    hasBurst: true,
  },
  "GD02-088": {
    code: "GD02-088",
    nameEn: "Flit Asuno",
    cardType: "PILOT",
    color: "green",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Earth Federation","Asuno Family","X-Rounder"],
    triggerKeywords: ["Burst","When Linked"],
    hasBurst: true,
  },
  "GD02-089": {
    code: "GD02-089",
    nameEn: "Lalah Sune",
    cardType: "PILOT",
    color: "green",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Zeon","Newtype"],
    effectKeywords: ["Breach"],
    triggerKeywords: ["Burst","When Paired"],
    keywordTags: ["Breach 1"],
    hasBurst: true,
  },
  "GD02-090": {
    code: "GD02-090",
    nameEn: "Challia Bull",
    cardType: "PILOT",
    color: "green",
    level: 5,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Zeon","Newtype"],
    triggerKeywords: ["Burst"],
    hasBurst: true,
  },
  "GD02-091": {
    code: "GD02-091",
    nameEn: "Haman Karn",
    cardType: "PILOT",
    color: "red",
    level: 5,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Neo Zeon","Newtype"],
    triggerKeywords: ["Burst","When Paired"],
    hasBurst: true,
  },
  "GD02-092": {
    code: "GD02-092",
    nameEn: "Shagia Frost",
    cardType: "PILOT",
    color: "red",
    level: 4,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["New UNE"],
    triggerKeywords: ["Burst","Attack","During Link"],
    hasBurst: true,
  },
  "GD02-093": {
    code: "GD02-093",
    nameEn: "Olba Frost",
    cardType: "PILOT",
    color: "red",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["New UNE"],
    triggerKeywords: ["Burst"],
    hasBurst: true,
  },
  "GD02-094": {
    code: "GD02-094",
    nameEn: "Garrod Ran & Tiffa Adill",
    cardType: "PILOT",
    color: "purple",
    level: 4,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Vulture","Newtype"],
    triggerKeywords: ["Burst","When Paired"],
    hasBurst: true,
  },
  "GD02-095": {
    code: "GD02-095",
    nameEn: "Lafter Frankland",
    cardType: "PILOT",
    color: "purple",
    level: 4,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Teiwaz"],
    triggerKeywords: ["Burst","Attack"],
    hasBurst: true,
  },
  "GD02-096": {
    code: "GD02-096",
    nameEn: "Desil Galette",
    cardType: "PILOT",
    color: "purple",
    level: 4,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Vagan","X-Rounder"],
    triggerKeywords: ["Burst","When Linked"],
    hasBurst: true,
  },
  "GD02-097": {
    code: "GD02-097",
    nameEn: "Kamille Bidan",
    cardType: "PILOT",
    color: "white",
    level: 5,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["AEUG","Newtype"],
    triggerKeywords: ["Burst"],
    hasBurst: true,
  },
  "GD02-098": {
    code: "GD02-098",
    nameEn: "Quattro Bajeena",
    cardType: "PILOT",
    color: "white",
    level: 4,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["AEUG","Newtype"],
    triggerKeywords: ["Burst","When Linked"],
    hasBurst: true,
  },
  "GD02-099": {
    code: "GD02-099",
    nameEn: "Gaelio Bauduin",
    cardType: "PILOT",
    color: "white",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Gjallarhorn"],
    triggerKeywords: ["Burst","When Paired"],
    hasBurst: true,
  },
  "GD02-106": {
    code: "GD02-106",
    nameEn: "White Wolf",
    cardType: "PILOT",
    color: "green",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 0,
    traits: ["Earth Federation"],
    triggerKeywords: ["Action"],
    pilotMode: {"pilotName":"Woolf Enneacle","ap":1,"hp":0},
  },
};
