import type { CardDef } from "../../engine/types";

export const PILOTS: Record<string, CardDef> = {
  "GD02-085": {
    code: "GD02-085",
    structuredSourceText: {
      onSelfHeal: "【During Link】【Once per Turn】During your turn, when this Unit recovers HP, if you have 4 or less cards in your hand, draw 1.",
    },
    nameEn: "Four Murasame",
    cardType: "PILOT",
    color: "blue",
    level: 5,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Titans","Cyber-Newtype"],
    triggerKeywords: ["Burst","During Link"],
    hasBurst: true,
    // "During Link, Once per Turn, during your turn, when this Unit recovers HP, if you
    // have 4 or less cards in your hand, draw 1." ("this Unit" = a Unit pareada.)
    onSelfHeal: { duringLinkOnly: true, oncePerTurn: true, requiresHandCountAtMost: 4, drawAmount: 1 },
  },
  "GD02-086": {
    code: "GD02-086",
    nameEn: "Jerid Messa",
    cardType: "PILOT",
    color: "blue",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Titans"],
    triggerKeywords: ["Burst"],
    hasBurst: true,
    // "this" = a Unit pareada; "another (Titans) Unit" exclui ela (E12)
    staticAbilities: [
      { condition: "duringPair", scope: "pairedUnit", stat: "ap", amount: 1, boardCondition: { kind: "friendlyOtherUnitTraitCountAtLeast", trait: "Titans", n: 1 }, sourceText: "While you have another (Titans) Unit in play, this gets AP+1." },
    ],
  },
  "GD02-087": {
    code: "GD02-087",
    nameEn: "Orga, Crot, and Shani",
    cardType: "PILOT",
    color: "blue",
    level: 5,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Earth Alliance","Biological CPU"],
    triggerKeywords: ["Burst","When Linked"],
    hasBurst: true,
  },
  "GD02-088": {
    code: "GD02-088",
    nameEn: "Flit Asuno",
    cardType: "PILOT",
    color: "green",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Earth Federation","Asuno Family","X-Rounder"],
    triggerKeywords: ["Burst","When Linked"],
    hasBurst: true,
  },
  "GD02-089": {
    code: "GD02-089",
    nameEn: "Lalah Sune",
    cardType: "PILOT",
    color: "green",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Zeon","Newtype"],
    // (sem effectKeywords: o <Breach 1> é concedido pelo 【When Paired】, o Pilot não tem keyword própria)
    triggerKeywords: ["Burst","When Paired"],
    hasBurst: true,
  },
  "GD02-090": {
    code: "GD02-090",
    nameEn: "Challia Bull",
    cardType: "PILOT",
    color: "green",
    level: 5,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Zeon","Newtype"],
    triggerKeywords: ["Burst"],
    hasBurst: true,
    staticAbilities: [
      { condition: "duringPair", scope: "pairedUnit", stat: "ap", amount: 1, boardCondition: { kind: "friendlyOtherUnitWithKeywordCountAtLeast", keyword: "High-Maneuver", n: 1 }, sourceText: "While you have another Unit with <High-Maneuver> in play, this Unit gets AP+1." },
    ],
  },
  "GD02-091": {
    code: "GD02-091",
    nameEn: "Haman Karn",
    cardType: "PILOT",
    color: "red",
    level: 5,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Neo Zeon","Newtype"],
    triggerKeywords: ["Burst","When Paired"],
    hasBurst: true,
  },
  "GD02-092": {
    code: "GD02-092",
    nameEn: "Shagia Frost",
    cardType: "PILOT",
    color: "red",
    level: 4,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["New UNE"],
    triggerKeywords: ["Burst","Attack","During Link"],
    hasBurst: true,
  },
  "GD02-093": {
    code: "GD02-093",
    structuredSourceText: {
      combatTriggers: "During your turn, when this Unit destroys an enemy Unit paired with a (Newtype) Pilot with battle damage, draw 1.",
    },
    nameEn: "Olba Frost",
    cardType: "PILOT",
    color: "red",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["New UNE"],
    triggerKeywords: ["Burst"],
    hasBurst: true,
    // "During your turn, when this Unit destroys an enemy Unit paired with a (Newtype) Pilot
    // with battle damage, draw 1." ("this Unit" = a Unit pareada com este Pilot.)
    combatTriggers: [{ condition: "always", on: "destroyEnemyInBattle", requiresEnemyPairedPilotTrait: "Newtype", action: { kind: "draw", amount: 1 } }],
  },
  "GD02-094": {
    code: "GD02-094",
    nameEn: "Garrod Ran & Tiffa Adill",
    cardType: "PILOT",
    color: "purple",
    level: 4,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Vulture","Newtype"],
    triggerKeywords: ["Burst","When Paired"],
    hasBurst: true,
  },
  "GD02-095": {
    code: "GD02-095",
    nameEn: "Lafter Frankland",
    cardType: "PILOT",
    color: "purple",
    level: 4,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Teiwaz"],
    triggerKeywords: ["Burst","Attack"],
    hasBurst: true,
  },
  "GD02-096": {
    code: "GD02-096",
    nameEn: "Desil Galette",
    cardType: "PILOT",
    color: "purple",
    level: 4,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Vagan","X-Rounder"],
    triggerKeywords: ["Burst","When Linked"],
    hasBurst: true,
  },
  "GD02-097": {
    code: "GD02-097",
    nameEn: "Kamille Bidan",
    cardType: "PILOT",
    color: "white",
    level: 5,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["AEUG","Newtype"],
    triggerKeywords: ["Burst"],
    hasBurst: true,
    staticAbilities: [
      { condition: "duringPair", scope: "pairedUnit", stat: "ap", amount: 2, boardCondition: { kind: "baseColorInPlay", color: "white" }, sourceText: "While there is a friendly white Base in play, this Unit gets AP+2." },
    ],
  },
  "GD02-098": {
    code: "GD02-098",
    structuredSourceText: {
      nameAliases: "This card's name is also treated as [Char Aznable].",
    },
    nameEn: "Quattro Bajeena",
    cardType: "PILOT",
    color: "white",
    level: 4,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["AEUG","Newtype"],
    triggerKeywords: ["Burst","When Linked"],
    hasBurst: true,
    // "This card's name is also treated as [Char Aznable]." Afeta link condition
    // pilotName de OUTRAS cartas (ex. GD02-032 White Gundam).
    nameAliases: ["Char Aznable"],
  },
  "GD02-099": {
    code: "GD02-099",
    nameEn: "Gaelio Bauduin",
    cardType: "PILOT",
    color: "white",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Gjallarhorn"],
    triggerKeywords: ["Burst","When Paired"],
    hasBurst: true,
  },
};
