import type { CardDef } from "../../engine/types";

export const UNITS_WHITE: Record<string, CardDef> = {
  "GD02-069": {
    code: "GD02-069",
    nameEn: "Zeta Gundam",
    cardType: "UNIT",
    color: "white",
    level: 6,
    cost: 5,
    ap: 5,
    hp: 4,
    traits: ["AEUG"],
    link: {"kind":"pilotName","values":["Kamille Bidan"]},
    triggerKeywords: ["During Link","Activate: Main"],
  },
  "GD02-070": {
    code: "GD02-070",
    nameEn: "Gundam Kimaris",
    cardType: "UNIT",
    color: "white",
    level: 5,
    cost: 4,
    ap: 4,
    hp: 4,
    traits: ["Gjallarhorn","Gundam Frame"],
    link: {"kind":"pilotName","values":["Gaelio Bauduin"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-071": {
    code: "GD02-071",
    nameEn: "Gundam Mk-II (AEUG)",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["AEUG"],
    link: {"kind":"trait","values":["AEUG"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-072": {
    code: "GD02-072",
    nameEn: "Hyaku-Shiki",
    cardType: "UNIT",
    color: "white",
    level: 5,
    cost: 3,
    ap: 4,
    hp: 4,
    traits: ["AEUG"],
    link: {"kind":"pilotName","values":["Quattro Bajeena"]},
    // <Blocker> é inato; <Repair 1> é CONDICIONAL ("While a friendly white Base is in play, ...")
    // — achado de dado (mesma classe de GD01-108/GD02-076): estava fixo em effectKeywords/keywordTags.
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
    staticAbilities: [{ condition: "always", scope: "self", keyword: "Repair", keywordValue: 1, boardCondition: { kind: "baseColorInPlay", color: "white" } }],
  },
  "GD02-073": {
    code: "GD02-073",
    nameEn: "Carta's Graze Ritter (Ground Type)",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 5,
    hp: 4,
    traits: ["Gjallarhorn"],
    link: {"kind":"pilotName","values":["Carta Issue"]},
  },
  "GD02-074": {
    code: "GD02-074",
    nameEn: "Gundam Aerial Rebuild",
    cardType: "UNIT",
    color: "white",
    level: 7,
    cost: 5,
    ap: 5,
    hp: 5,
    traits: ["Academy"],
    link: {"kind":"pilotName","values":["Suletta Mercury"]},
    // <High-Maneuver> é inato; <Blocker> é CONDICIONAL a "During Pair" + trash Command>=4
    // — achado de dado: High-Maneuver faltava e Blocker estava fixo incondicional.
    effectKeywords: ["High-Maneuver"],
    triggerKeywords: ["During Pair"],
    keywordTags: ["High-Maneuver"],
    staticAbilities: [
      { condition: "duringPair", scope: "self", keyword: "Blocker", boardCondition: { kind: "trashCardTypeCountAtLeast", cardType: "COMMAND", n: 4 } },
    ],
  },
  "GD02-075": {
    code: "GD02-075",
    nameEn: "Rick Dias (Red)",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["AEUG"],
    link: {"kind":"trait","values":["AEUG"]},
    triggerKeywords: ["Attack"],
  },
  "GD02-076": {
    code: "GD02-076",
    nameEn: "Buster Gundam",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Triple Ship Alliance"],
    link: {"kind":"trait","values":["Coordinator"]},
    // <Blocker> é CONDICIONAL ("While this Unit has 5 or more AP, ...") — achado de dado
    // (mesma classe de GD01-108/GD02-072): estava fixo em effectKeywords/keywordTags.
    staticAbilities: [{ condition: "always", scope: "self", keyword: "Blocker", targetCondition: { kind: "apAtLeast", n: 5 } }],
  },
  "GD02-077": {
    code: "GD02-077",
    nameEn: "Ein's Schwalbe Graze",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Gjallarhorn"],
    link: {"kind":"trait","values":["Gjallarhorn"]},
  },
  "GD02-078": {
    code: "GD02-078",
    nameEn: "Gundam Pharact",
    cardType: "UNIT",
    color: "white",
    level: 5,
    cost: 3,
    ap: 5,
    hp: 4,
    traits: ["Academy"],
    link: {"kind":"pilotName","values":["Elan Ceres"]},
  },
  "GD02-079": {
    code: "GD02-079",
    nameEn: "Rick Dias",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["AEUG"],
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
  },
  "GD02-080": {
    code: "GD02-080",
    nameEn: "Nemo",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 2,
    traits: ["AEUG"],
  },
  "GD02-081": {
    code: "GD02-081",
    nameEn: "Methuss",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 1,
    hp: 1,
    traits: ["AEUG"],
    link: {"kind":"pilotName","values":["Fa Yuiry"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-082": {
    code: "GD02-082",
    nameEn: "Gaelio's Schwalbe Graze",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Gjallarhorn"],
    link: {"kind":"pilotName","values":["Gaelio Bauduin"]},
  },
  "GD02-083": {
    code: "GD02-083",
    nameEn: "Graze Ritter (Ground Type)",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Gjallarhorn"],
    triggerKeywords: ["Destroyed"],
  },
  "GD02-084": {
    code: "GD02-084",
    nameEn: "Lauda's Dilanza",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 1,
    hp: 3,
    traits: ["Academy"],
    link: {"kind":"trait","values":["Academy"]},
  },
};
