import type { CardDef } from "../../engine/types";

export const UNITS_RED: Record<string, CardDef> = {
  "GD02-036": {
    code: "GD02-036",
    nameEn: "Qubeley",
    cardType: "UNIT",
    color: "red",
    level: 7,
    cost: 5,
    ap: 5,
    hp: 5,
    traits: ["Neo Zeon"],
    link: {"kind":"pilotName","values":["Haman Karn"]},
    triggerKeywords: ["Attack","When Linked","During Pair"],
  },
  "GD02-037": {
    code: "GD02-037",
    nameEn: "Gundam Virsago",
    cardType: "UNIT",
    color: "red",
    level: 5,
    cost: 4,
    ap: 4,
    hp: 4,
    traits: ["New UNE"],
    link: {"kind":"pilotName","values":["Shagia Frost"]},
    effectKeywords: ["Breach"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["Breach 1"],
  },
  "GD02-038": {
    code: "GD02-038",
    nameEn: "GQuuuuuuX (Omega Psycommu)",
    cardType: "UNIT",
    color: "red",
    level: 7,
    cost: 5,
    ap: 5,
    hp: 4,
    traits: ["Clan"],
    link: {"kind":"pilotName","values":["Amate Yuzuriha (Machu)"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-039": {
    code: "GD02-039",
    nameEn: "Haman Karn's Gaza C",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Neo Zeon"],
    link: {"kind":"pilotName","values":["Haman Karn"]},
    triggerKeywords: ["When Paired"],
  },
  "GD02-040": {
    code: "GD02-040",
    nameEn: "Gundam Ashtaron",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["New UNE"],
    link: {"kind":"trait","values":["New UNE"]},
    effectKeywords: ["Support"],
    triggerKeywords: ["Deploy","Activate: Main"],
    keywordTags: ["Support 2"],
  },
  "GD02-041": {
    code: "GD02-041",
    nameEn: "Sugai's Gelgoog",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 4,
    ap: 3,
    hp: 3,
    traits: ["Clan"],
    link: {"kind":"pilotName","values":["Shiiko Sugai"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-042": {
    code: "GD02-042",
    nameEn: "Gundam Ashtaron (MA Mode)",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["New UNE"],
    link: {"kind":"pilotName","values":["Olba Frost"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-043": {
    code: "GD02-043",
    nameEn: "Daughtress Weapon",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 1,
    traits: ["New UNE"],
    triggerKeywords: ["Deploy"],
  },
  "GD02-044": {
    code: "GD02-044",
    nameEn: "Daughtress Command",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 1,
    traits: ["New UNE"],
    triggerKeywords: ["Destroyed"],
  },
  "GD02-045": {
    code: "GD02-045",
    nameEn: "GINN Long-Range Reconnaissance Type",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 1,
    hp: 1,
    traits: ["ZAFT"],
    triggerKeywords: ["Attack"],
  },
  "GD02-046": {
    code: "GD02-046",
    nameEn: "Sayla's Light-Type Guncannon",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 4,
    ap: 3,
    hp: 4,
    traits: ["Earth Federation"],
    link: {"kind":"pilotName","values":["Sayla Mass"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-047": {
    code: "GD02-047",
    nameEn: "Gaza C",
    cardType: "UNIT",
    color: "red",
    level: 1,
    cost: 1,
    ap: 0,
    hp: 1,
    traits: ["Neo Zeon"],
  },
  "GD02-048": {
    code: "GD02-048",
    nameEn: "Zaku III (Sleeves)",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 4,
    hp: 1,
    traits: ["Neo Zeon"],
    link: {"kind":"trait","values":["Neo Zeon"]},
  },
  "GD02-049": {
    code: "GD02-049",
    nameEn: "Daughtress",
    cardType: "UNIT",
    color: "red",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["New UNE"],
    effectKeywords: ["Support"],
    keywordTags: ["Support 1"],
  },
  "GD02-050": {
    code: "GD02-050",
    nameEn: "Ga-Zowmn (Sleeves)",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Neo Zeon"],
  },
  "GD02-051": {
    code: "GD02-051",
    nameEn: "01 Gundam",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Earth Federation"],
  },
  "GD02-052": {
    code: "GD02-052",
    nameEn: "Guncannon",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Earth Federation"],
  },
};
