import type { CardDef } from "../../engine/types";

export const UNITS_PURPLE: Record<string, CardDef> = {
  "GD02-053": {
    code: "GD02-053",
    structuredSourceText: {
      staticAbilities: "【During Link】During your turn, while there are 7 or more cards in your trash, all your other (Vulture) Units get AP+2.",
    },
    nameEn: "Gundam X (GD02-053)",
    cardType: "UNIT",
    color: "purple",
    level: 7,
    cost: 5,
    ap: 6,
    hp: 5,
    traits: ["Vulture"],
    link: {"kind":"pilotName","values":["Garrod Ran"]},
    triggerKeywords: ["During Link"],
    effectKeywords: ["Suppression"],
    keywordTags: ["Suppression"],
    // "During Link, during your turn, while there are 7 or more cards in your trash, all your other (Vulture) Units get AP+2."
    staticAbilities: [
      {
        condition: "duringLink",
        scope: "allFriendlyUnits",
        stat: "ap",
        amount: 2,
        excludeSelf: true,
        duringYourTurnOnly: true,
        boardCondition: { kind: "trashCountAtLeast", n: 7 },
        targetCondition: { kind: "traitIs", trait: "Vulture" },
      },
    ],
  },
  "GD02-054": {
    code: "GD02-054",
    nameEn: "Gundam Barbatos 1st Form",
    cardType: "UNIT",
    color: "purple",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Tekkadan","Gundam Frame"],
    link: {"kind":"pilotName","values":["Mikazuki Augus"]},
    triggerKeywords: ["Attack"],
  },
  "GD02-055": {
    code: "GD02-055",
    nameEn: "Gundam Gusion Rebake",
    cardType: "UNIT",
    color: "purple",
    level: 5,
    cost: 4,
    ap: 3,
    hp: 5,
    traits: ["Tekkadan","Gundam Frame"],
    link: {"kind":"pilotName","values":["Akihiro Altland"]},
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["Blocker"],
  },
  "GD02-056": {
    code: "GD02-056",
    nameEn: "Gundam X (GD02-056)",
    cardType: "UNIT",
    color: "purple",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Vulture"],
    link: {"kind":"pilotName","values":["Garrod Ran"]},
    triggerKeywords: ["During Pair","Destroyed"],
  },
  "GD02-057": {
    code: "GD02-057",
    nameEn: "Zedas",
    cardType: "UNIT",
    color: "purple",
    level: 5,
    cost: 3,
    ap: 5,
    hp: 3,
    traits: ["UE","Vagan"],
    link: {"kind":"pilotName","values":["Desil Galette"]},
    triggerKeywords: ["Attack","During Pair"],
  },
  "GD02-058": {
    code: "GD02-058",
    nameEn: "Ryusei-Go (Graze Custom II)",
    cardType: "UNIT",
    color: "purple",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Tekkadan"],
    link: {"kind":"trait","values":["Tekkadan"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-059": {
    code: "GD02-059",
    nameEn: "Gundam Airmaster",
    cardType: "UNIT",
    color: "purple",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Vulture"],
    link: {"kind":"trait","values":["Vulture"]},
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
  },
  "GD02-060": {
    code: "GD02-060",
    nameEn: "Gundam Leopard",
    cardType: "UNIT",
    color: "purple",
    level: 5,
    cost: 4,
    ap: 4,
    hp: 4,
    traits: ["Vulture"],
    link: {"kind":"pilotName","values":["Roybea Loy"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-061": {
    code: "GD02-061",
    nameEn: "Hyakuri",
    cardType: "UNIT",
    color: "purple",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Teiwaz"],
    link: {"kind":"trait","values":["Teiwaz"]},
    triggerKeywords: ["When Paired"],
  },
  "GD02-062": {
    code: "GD02-062",
    nameEn: "Amida's Hyakuren",
    cardType: "UNIT",
    color: "purple",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Teiwaz"],
    link: {"kind":"trait","values":["Teiwaz"]},
  },
  "GD02-063": {
    code: "GD02-063",
    nameEn: "Gundam Airmaster (Fighter Mode)",
    cardType: "UNIT",
    color: "purple",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Vulture"],
    link: {"kind":"trait","values":["Vulture"]},
  },
  "GD02-064": {
    code: "GD02-064",
    structuredSourceText: {
      innateEffectDamageProtection: "During your turn, while there are 7 or more cards in your trash, this Unit can't receive effect damage from enemy Commands.",
    },
    nameEn: "Gundam Leopard (GD02-064)",
    cardType: "UNIT",
    color: "purple",
    level: 5,
    cost: 4,
    ap: 4,
    hp: 4,
    traits: ["Vulture"],
    link: {"kind":"trait","values":["Vulture"]},
    // "During your turn, while there are 7 or more cards in your trash, this Unit can't
    // receive effect damage from enemy Commands."
    innateEffectDamageProtection: { fromCardType: "COMMAND", duringYourTurnOnly: true, requiresTrashCountAtLeast: 7 },
  },
  "GD02-065": {
    code: "GD02-065",
    nameEn: "Jenice Custom",
    cardType: "UNIT",
    color: "purple",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Vulture"],
  },
  "GD02-066": {
    code: "GD02-066",
    structuredSourceText: {
      attackTargetRules: "This Unit can't choose the enemy player as its attack target.",
    },
    nameEn: "Gafran",
    cardType: "UNIT",
    color: "purple",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 3,
    traits: ["UE","Vagan"],
    // "This Unit can't choose the enemy player as its attack target." — mesmo padrão de ST01-009 Zowort.
    attackTargetRules: { cannotTargetPlayer: true },
  },
  "GD02-067": {
    code: "GD02-067",
    nameEn: "Baqto",
    cardType: "UNIT",
    color: "purple",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["UE","Vagan"],
  },
  "GD02-068": {
    code: "GD02-068",
    nameEn: "Gundam Barbatos 3rd Form",
    cardType: "UNIT",
    color: "purple",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 5,
    traits: ["Tekkadan","Gundam Frame"],
    link: {"kind":"trait","values":["Tekkadan"]},
    triggerKeywords: ["Deploy"],
  },
};
