import type { CardDef } from "../../engine/types";

export const UNITS_GREEN: Record<string, CardDef> = {
  "GD02-020": {
    code: "GD02-020",
    nameEn: "Elmeth",
    cardType: "UNIT",
    color: "green",
    level: 6,
    cost: 5,
    ap: 4,
    hp: 4,
    traits: ["Zeon"],
    link: {"kind":"pilotName","values":["Lalah Sune"]},
    triggerKeywords: ["Deploy","During Link"],
    // 【During Link】 This Unit gets AP+2. (era spec com gatilho "DuringLink", que o motor não dispara)
    staticAbilities: [{ condition: "duringLink", scope: "self", stat: "ap", amount: 2, sourceText: "【During Link】 This Unit gets AP+2." }],
  },
  "GD02-021": {
    code: "GD02-021",
    nameEn: "Gundam AGE-1 Normal",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"trait","values":["Asuno Family"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-022": {
    code: "GD02-022",
    nameEn: "G-Exes",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Earth Federation"],
    link: {"kind":"pilotName","values":["Woolf Enneacle"]},
    // "Once per Turn, when you place an EX Resource, choose 1 of your (AGE System) Units. It
    // gains <Breach 2> during this turn." — achado de dado: Breach2 estava fixo em
    // effectKeywords/keywordTags nesta própria carta, quando o texto real é condicional
    // (gatilho de EX Resource) E concedido a uma Unit ESCOLHIDA (não necessariamente esta).
    onExResourcePlaced: { oncePerTurn: true, grantKeyword: "Breach 2", requiresTargetTrait: "AGE System" },
  },
  "GD02-023": {
    code: "GD02-023",
    nameEn: "Gundam AGE-1 Spallow",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"pilotName","values":["Flit Asuno"]},
    triggerKeywords: ["During Link"],
    staticAbilities: [
      { condition: "duringLink", scope: "self", keyword: "First Strike", boardCondition: { kind: "controllerLevelAtLeast", n: 7 }, sourceText: "【During Link】While you are Lv.7 or higher, this Unit gains <First Strike>." },
    ],
  },
  "GD02-024": {
    code: "GD02-024",
    nameEn: "Red Gundam",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 3,
    ap: 4,
    hp: 4,
    traits: ["Clan"],
    link: {"kind":"trait","values":["Clan"]},
    triggerKeywords: ["During Link"],
    // "During Link, This Unit gains <High-Maneuver>."
    staticAbilities: [{ condition: "duringLink", scope: "self", keyword: "High-Maneuver" }],
  },
  "GD02-025": {
    code: "GD02-025",
    nameEn: "Gundam Heavyarms",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Operation Meteor"],
    link: {"kind":"trait","values":["Operation Meteor"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-026": {
    code: "GD02-026",
    nameEn: "Genoace Custom",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Earth Federation"],
    link: {"kind":"pilotName","values":["Woolf Enneacle"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-027": {
    code: "GD02-027",
    nameEn: "Gundam AGE-1 Titus (GD02-027)",
    cardType: "UNIT",
    color: "green",
    level: 7,
    cost: 4,
    ap: 5,
    hp: 5,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"pilotName","values":["Flit Asuno"]},
    effectKeywords: ["Breach"],
    keywordTags: ["Breach 3"],
  },
  "GD02-028": {
    code: "GD02-028",
    nameEn: "Abdul's Maganac",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Maganac Corps"],
    link: {"kind":"trait","values":["Maganac Corps"]},
  },
  "GD02-029": {
    code: "GD02-029",
    nameEn: "Gundam AGE-1 Normal (GD02-029)",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"trait","values":["Asuno Family"]},
  },
  "GD02-030": {
    code: "GD02-030",
    nameEn: "Genoace",
    cardType: "UNIT",
    color: "green",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Earth Federation"],
  },
  "GD02-031": {
    code: "GD02-031",
    nameEn: "Gundam AGE-1 Titus",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 2,
    ap: 2,
    hp: 4,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"pilotName","values":["Flit Asuno"]},
    staticAbilities: [
      { condition: "always", scope: "self", stat: "ap", amount: 2, boardCondition: { kind: "controllerLevelAtLeast", n: 7 }, sourceText: "While you are Lv.7 or higher, this Unit gets AP+2." },
    ],
  },
  "GD02-032": {
    code: "GD02-032",
    nameEn: "White Gundam",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Zeon"],
    link: {"kind":"pilotName","values":["Char Aznable"]},
  },
  "GD02-033": {
    code: "GD02-033",
    nameEn: "Kikeroga (MA Mode)",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 4,
    ap: 3,
    hp: 4,
    traits: ["Zeon"],
    link: {"kind":"pilotName","values":["Challia Bull"]},
    staticAbilities: [
      { condition: "always", scope: "self", keyword: "Breach", keywordValue: 5, boardCondition: { kind: "friendlyOtherLinkUnitTraitCountAtLeast", trait: "Zeon", n: 1 }, sourceText: "While another friendly (Zeon) Link Unit is in play, this Unit gains <Breach 5>." },
    ],
  },
  "GD02-034": {
    code: "GD02-034",
    nameEn: "GQuuuuuuX",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 3,
    traits: ["Zeon"],
    triggerKeywords: ["During Pair"],
    staticAbilities: [
      { condition: "duringPair", scope: "self", stat: "ap", amount: 2, boardCondition: { kind: "pairedPilotColorIs", color: "red" }, sourceText: "【During Pair･Red Pilot】This Unit gets AP+2." },
    ],
  },
  "GD02-035": {
    code: "GD02-035",
    nameEn: "Police Zaku (Armored RRU Type)",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 3,
    traits: ["Side 6"],
    // "This Unit can't choose the enemy player as its attack target." — mesmo padrão de ST01-009 Zowort.
    attackTargetRules: { cannotTargetPlayer: true },
  },
};
