import type { CardDef } from "../../engine/types";

export const UNITS_GREEN: Record<string, CardDef> = {
  "GD02-020": {
    code: "GD02-020",
    nameEn: "Elmeth",
    cardType: "UNIT",
    color: "green",
    level: 6,
    cost: 5,
    ap: 4,
    hp: 4,
    traits: ["Zeon"],
    link: {"kind":"pilotName","values":["Lalah Sune"]},
    triggerKeywords: ["Deploy","During Link"],
  },
  "GD02-021": {
    code: "GD02-021",
    nameEn: "Gundam AGE-1 Normal",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"trait","values":["Asuno Family"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-022": {
    code: "GD02-022",
    nameEn: "G-Exes",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Earth Federation"],
    link: {"kind":"pilotName","values":["Woolf Enneacle"]},
    effectKeywords: ["Breach"],
    keywordTags: ["Breach 2"],
  },
  "GD02-023": {
    code: "GD02-023",
    nameEn: "Gundam AGE-1 Spallow",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"pilotName","values":["Flit Asuno"]},
    triggerKeywords: ["During Link"],
  },
  "GD02-024": {
    code: "GD02-024",
    nameEn: "Red Gundam",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 3,
    ap: 4,
    hp: 4,
    traits: ["Clan"],
    link: {"kind":"trait","values":["Clan"]},
    triggerKeywords: ["During Link"],
    // "During Link, This Unit gains <High-Maneuver>."
    staticAbilities: [{ condition: "duringLink", scope: "self", keyword: "High-Maneuver" }],
  },
  "GD02-025": {
    code: "GD02-025",
    nameEn: "Gundam Heavyarms",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Operation Meteor"],
    link: {"kind":"trait","values":["Operation Meteor"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-026": {
    code: "GD02-026",
    nameEn: "Genoace Custom",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Earth Federation"],
    link: {"kind":"pilotName","values":["Woolf Enneacle"]},
    triggerKeywords: ["Deploy"],
  },
  "GD02-027": {
    code: "GD02-027",
    nameEn: "Gundam AGE-1 Titus (GD02-027)",
    cardType: "UNIT",
    color: "green",
    level: 7,
    cost: 4,
    ap: 5,
    hp: 5,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"pilotName","values":["Flit Asuno"]},
  },
  "GD02-028": {
    code: "GD02-028",
    nameEn: "Abdul's Maganac",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Maganac Corps"],
    link: {"kind":"trait","values":["Maganac Corps"]},
  },
  "GD02-029": {
    code: "GD02-029",
    nameEn: "Gundam AGE-1 Normal (GD02-029)",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"trait","values":["Asuno Family"]},
  },
  "GD02-030": {
    code: "GD02-030",
    nameEn: "Genoace",
    cardType: "UNIT",
    color: "green",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Earth Federation"],
  },
  "GD02-031": {
    code: "GD02-031",
    nameEn: "Gundam AGE-1 Titus",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 2,
    ap: 2,
    hp: 4,
    traits: ["Earth Federation","AGE System"],
    link: {"kind":"pilotName","values":["Flit Asuno"]},
  },
  "GD02-032": {
    code: "GD02-032",
    nameEn: "White Gundam",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Zeon"],
    link: {"kind":"pilotName","values":["Char Aznable"]},
  },
  "GD02-033": {
    code: "GD02-033",
    nameEn: "Kikeroga (MA Mode)",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 4,
    ap: 3,
    hp: 4,
    traits: ["Zeon"],
    link: {"kind":"pilotName","values":["Challia Bull"]},
  },
  "GD02-034": {
    code: "GD02-034",
    nameEn: "GQuuuuuuX",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 3,
    traits: ["Zeon"],
    triggerKeywords: ["During Pair"],
  },
  "GD02-035": {
    code: "GD02-035",
    nameEn: "Police Zaku (Armored RRU Type)",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 3,
    traits: ["Side 6"],
    // "This Unit can't choose the enemy player as its attack target." — mesmo padrão de ST01-009 Zowort.
    attackTargetRules: { cannotTargetPlayer: true },
  },
};
