import type { CardDef } from "../../engine/types";

export const UNITS_BLUE: Record<string, CardDef> = {
  "GD02-001": {
    code: "GD02-001",
    nameEn: "Psycho Gundam",
    cardType: "UNIT",
    color: "blue",
    level: 6,
    cost: 4,
    ap: 4,
    hp: 5,
    traits: ["Titans"],
    link: {"kind":"pilotName","values":["Four Murasame"]},
    effectKeywords: ["Breach"],
    triggerKeywords: ["During Pair"],
    keywordTags: ["Breach 3"],
  },
  "GD02-002": {
    code: "GD02-002",
    nameEn: "Gundam Epyon",
    cardType: "UNIT",
    color: "blue",
    level: 8,
    cost: 7,
    ap: 6,
    hp: 6,
    traits: ["White Fang"],
    link: {"kind":"pilotName","values":["Zechs Merquise"]},
    triggerKeywords: ["During Link"],
  },
  "GD02-003": {
    code: "GD02-003",
    nameEn: "Gundam Mk-II (Titans)",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 2,
    traits: ["Titans"],
    link: {"kind":"trait","values":["Titans"]},
    triggerKeywords: ["During Pair","Destroyed"],
  },
  "GD02-004": {
    code: "GD02-004",
    nameEn: "Byarlant",
    cardType: "UNIT",
    color: "blue",
    level: 5,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Titans"],
    link: {"kind":"pilotName","values":["Jerid Messa"]},
    triggerKeywords: ["When Paired"],
  },
  "GD02-005": {
    code: "GD02-005",
    nameEn: "Tallgeese",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 4,
    ap: 3,
    hp: 4,
    traits: ["OZ"],
    link: {"kind":"trait","values":["OZ"]},
    triggerKeywords: ["Attack","During Link"],
  },
  "GD02-006": {
    code: "GD02-006",
    nameEn: "Forbidden Gundam",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 4,
    ap: 4,
    hp: 4,
    traits: ["Earth Alliance"],
    link: {"kind":"trait","values":["Biological CPU"]},
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
  },
  "GD02-007": {
    code: "GD02-007",
    nameEn: "Psycho Gundam (MA Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 5,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Titans"],
    link: {"kind":"trait","values":["Cyber-Newtype"]},
    effectKeywords: ["Repair"],
    keywordTags: ["Repair 2"],
  },
  "GD02-008": {
    code: "GD02-008",
    nameEn: "Gabthley",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Titans"],
    link: {"kind":"trait","values":["Titans"]},
    triggerKeywords: ["When Linked"],
  },
  "GD02-009": {
    code: "GD02-009",
    nameEn: "Calamity Gundam",
    cardType: "UNIT",
    color: "blue",
    level: 5,
    cost: 3,
    ap: 3,
    hp: 5,
    traits: ["Earth Alliance"],
    link: {"kind":"trait","values":["Biological CPU"]},
  },
  "GD02-010": {
    code: "GD02-010",
    nameEn: "Raider Gundam",
    cardType: "UNIT",
    color: "blue",
    level: 5,
    cost: 3,
    ap: 4,
    hp: 4,
    traits: ["Earth Alliance"],
    link: {"kind":"trait","values":["Biological CPU"]},
  },
  "GD02-011": {
    code: "GD02-011",
    nameEn: "Moebius (Peacemaker Team)",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 2,
    ap: 0,
    hp: 1,
    traits: ["Earth Alliance"],
  },
  "GD02-012": {
    code: "GD02-012",
    nameEn: "Core Booster",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Earth Federation","White Base Team"],
    link: {"kind":"trait","values":["White Base Team"]},
  },
  "GD02-013": {
    code: "GD02-013",
    nameEn: "Hizack",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 2,
    traits: ["Titans"],
  },
  "GD02-014": {
    code: "GD02-014",
    nameEn: "Galbaldy Beta",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 1,
    traits: ["Titans"],
    triggerKeywords: ["Deploy"],
  },
  "GD02-015": {
    code: "GD02-015",
    nameEn: "Marasai",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Titans"],
    link: {"kind":"trait","values":["Titans"]},
  },
  "GD02-016": {
    code: "GD02-016",
    nameEn: "Barzam",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Titans"],
    triggerKeywords: ["Deploy"],
  },
  "GD02-017": {
    code: "GD02-017",
    nameEn: "Delta Plus (Waverider Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Earth Federation"],
    link: {"kind":"pilotName","values":["Riddhe Marcenas"]},
    effectKeywords: ["Repair"],
    keywordTags: ["Repair 2"],
  },
  "GD02-018": {
    code: "GD02-018",
    nameEn: "Taurus",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["OZ"],
    // "This Unit can't choose the enemy player as its attack target." — mesmo padrão de ST01-009 Zowort.
    attackTargetRules: { cannotTargetPlayer: true },
  },
  "GD02-019": {
    code: "GD02-019",
    nameEn: "Raider Gundam (MA Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Earth Alliance"],
    link: {"kind":"trait","values":["Biological CPU"]},
  },
};
