import type { CardDef } from "../../engine/types";

export const BASES: Record<string, CardDef> = {
  "GD01-123": {
    code: "GD01-123",
    nameEn: "Nahel Argama",
    cardType: "BASE",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 0,
    hp: 5,
    traits: ["Earth Federation","Warship"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-124": {
    code: "GD01-124",
    nameEn: "Side 7",
    cardType: "BASE",
    color: "blue",
    level: 1,
    cost: 1,
    ap: 0,
    hp: 4,
    traits: ["Earth Federation","Stronghold"],
    triggerKeywords: ["Deploy","Activate·Main","Burst"],
    hasBurst: true,
  },
  "GD01-125": {
    code: "GD01-125",
    nameEn: "Zanzibar",
    cardType: "BASE",
    color: "green",
    level: 4,
    cost: 2,
    ap: 0,
    hp: 5,
    traits: ["Zeon","Warship"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-126": {
    code: "GD01-126",
    nameEn: "Underground Desert Base",
    cardType: "BASE",
    color: "green",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 6,
    traits: ["Maganac Corps","Stronghold"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-127": {
    code: "GD01-127",
    nameEn: "Gamow",
    cardType: "BASE",
    color: "red",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 5,
    traits: ["ZAFT","Warship"],
    // "Breach 3" NÃO é keyword estática do próprio Gamow (Base, AP0, não ataca) —
    // é concedida a uma Unit escolhida via 【Activate･Action】 (GAMOW_ACTIVATE_ACTION).
    triggerKeywords: ["Deploy","Activate·Action","Burst"],
    hasBurst: true,
  },
  "GD01-128": {
    code: "GD01-128",
    nameEn: "Mining Asteroid Palau",
    cardType: "BASE",
    color: "red",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 6,
    traits: ["Neo Zeon","Stronghold"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-129": {
    code: "GD01-129",
    nameEn: "Kusanagi",
    cardType: "BASE",
    color: "white",
    level: 4,
    cost: 2,
    ap: 0,
    hp: 4,
    traits: ["Triple Ship Alliance","Warship"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-130": {
    code: "GD01-130",
    nameEn: "13th Tactical Testing Sector",
    cardType: "BASE",
    color: "white",
    level: 3,
    cost: 1,
    ap: 0,
    hp: 5,
    traits: ["Academy","Stronghold"],
    triggerKeywords: ["Deploy","Activate·Main","Burst"],
    hasBurst: true,
  },
};
