import type { CardDef } from "../../engine/types";

export const COMMANDS: Record<string, CardDef> = {
  "GD01-099": {
    code: "GD01-099",
    nameEn: "Intercept Orders",
    cardType: "COMMAND",
    color: "blue",
    level: 4,
    cost: 2,
    triggerKeywords: ["Main","Action","Burst"],
    hasBurst: true,
  },
  "GD01-100": {
    code: "GD01-100",
    nameEn: "A Show of Resolve",
    cardType: "COMMAND",
    color: "blue",
    level: 4,
    cost: 3,
    triggerKeywords: ["Main"],
  },
  "GD01-101": {
    code: "GD01-101",
    nameEn: "Deep Devotion",
    cardType: "COMMAND",
    color: "blue",
    level: 2,
    cost: 1,
    traits: ["OZ"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-102": {
    code: "GD01-102",
    nameEn: "Securing the Supply Line",
    cardType: "COMMAND",
    color: "blue",
    level: 4,
    cost: 2,
    triggerKeywords: ["Main"],
  },
  "GD01-103": {
    code: "GD01-103",
    nameEn: "The Stubborn Cog",
    cardType: "COMMAND",
    color: "blue",
    level: 1,
    cost: 1,
    traits: ["Earth Federation"],
    triggerKeywords: ["Main"],
  },
  "GD01-104": {
    code: "GD01-104",
    nameEn: "Signs of a Revolution",
    cardType: "COMMAND",
    color: "blue",
    level: 3,
    cost: 2,
    triggerKeywords: ["Main","Burst"],
    hasBurst: true,
  },
  "GD01-105": {
    code: "GD01-105",
    nameEn: "Citizens, Take a Stand!",
    cardType: "COMMAND",
    color: "green",
    level: 4,
    cost: 1,
    triggerKeywords: ["Main","Burst"],
    hasBurst: true,
  },
  "GD01-106": {
    code: "GD01-106",
    nameEn: "Fortress Defense",
    cardType: "COMMAND",
    color: "green",
    level: 5,
    cost: 2,
    traits: ["Zeon"],
    triggerKeywords: ["Main"],
  },
  "GD01-107": {
    code: "GD01-107",
    nameEn: "First Contact",
    cardType: "COMMAND",
    color: "green",
    level: 3,
    cost: 3,
    triggerKeywords: ["Main","Burst"],
    hasBurst: true,
  },
  "GD01-108": {
    code: "GD01-108",
    nameEn: "Strategic Arms",
    cardType: "COMMAND",
    color: "green",
    level: 6,
    cost: 6,
    // "Blocker" no texto oficial é o FILTRO do alvo ("all Units with <Blocker>"),
    // não uma keyword da própria carta — Fase 1 (Gemini) tinha marcado errado
    // como effectKeywords/keywordTags do Command. Corrigido ao autorar o
    // EffectSpec (STRATEGIC_ARMS_MAIN).
    triggerKeywords: ["Main"],
  },
  "GD01-109": {
    code: "GD01-109",
    nameEn: "The Path to Victory or Defeat",
    cardType: "COMMAND",
    color: "green",
    level: 5,
    cost: 1,
    triggerKeywords: ["Main"],
  },
  "GD01-110": {
    code: "GD01-110",
    nameEn: "Rasid's Orders",
    cardType: "COMMAND",
    color: "green",
    level: 3,
    cost: 1,
    traits: ["Maganac Corps"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-111": {
    code: "GD01-111",
    nameEn: "Battle of Aces",
    cardType: "COMMAND",
    color: "red",
    level: 3,
    cost: 2,
    triggerKeywords: ["Main","Action","Burst"],
    hasBurst: true,
  },
  "GD01-112": {
    code: "GD01-112",
    nameEn: "Extreme Hatred",
    cardType: "COMMAND",
    color: "red",
    level: 6,
    cost: 1,
    traits: ["Zeon","Newtype"],
    triggerKeywords: ["Main"],
  },
  "GD01-113": {
    code: "GD01-113",
    nameEn: "The Desert Tiger",
    cardType: "COMMAND",
    color: "red",
    level: 3,
    cost: 1,
    traits: ["ZAFT","Coordinator"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-114": {
    code: "GD01-114",
    nameEn: "Assault on Torrington Base",
    cardType: "COMMAND",
    color: "red",
    level: 1,
    cost: 1,
    traits: ["Zeon"],
    triggerKeywords: ["Action"],
  },
  "GD01-115": {
    code: "GD01-115",
    nameEn: "Zeon Remnant Forces",
    cardType: "COMMAND",
    color: "red",
    level: 2,
    cost: 1,
    triggerKeywords: ["Main","Action"],
  },
  "GD01-116": {
    code: "GD01-116",
    nameEn: "Stealth Stratagem",
    cardType: "COMMAND",
    color: "red",
    level: 2,
    cost: 1,
    traits: ["ZAFT","Coordinator"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-117": {
    code: "GD01-117",
    nameEn: "The Witch and the Bride",
    cardType: "COMMAND",
    color: "white",
    level: 5,
    cost: 2,
    triggerKeywords: ["Main","Action","Burst"],
    hasBurst: true,
  },
  "GD01-118": {
    code: "GD01-118",
    nameEn: "Overflowing Affection",
    cardType: "COMMAND",
    color: "white",
    level: 2,
    cost: 1,
    triggerKeywords: ["Main"],
  },
  "GD01-119": {
    code: "GD01-119",
    nameEn: "Iron-Fisted Discipline",
    cardType: "COMMAND",
    color: "white",
    level: 2,
    cost: 1,
    traits: ["Academy"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-120": {
    code: "GD01-120",
    nameEn: "Naval Bombardment",
    cardType: "COMMAND",
    color: "white",
    level: 2,
    cost: 1,
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Action","Burst"],
    keywordTags: ["Blocker"],
    hasBurst: true,
  },
  "GD01-121": {
    code: "GD01-121",
    nameEn: "Midair Modifications",
    cardType: "COMMAND",
    color: "white",
    level: 3,
    cost: 2,
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Main","Burst"],
    keywordTags: ["Blocker"],
    hasBurst: true,
  },
  "GD01-122": {
    code: "GD01-122",
    nameEn: "Covert Operative",
    cardType: "COMMAND",
    color: "white",
    level: 3,
    cost: 1,
    traits: ["Academy"],
    triggerKeywords: ["Main"],
  },
};
