import type { CardDef } from "../../engine/types";

export const UNITS_RED: Record<string, CardDef> = {
  "GD01-044": {
    code: "GD01-044",
    nameEn: "Kshatriya",
    cardType: "UNIT",
    color: "red",
    level: 5,
    cost: 4,
    ap: 5,
    hp: 4,
    traits: ["Neo Zeon"],
    link: {"kind":"pilotName","values":["Marida Cruz"]},
  },
  "GD01-045": {
    code: "GD01-045",
    nameEn: "Duel Gundam (Assault Shroud)",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 4,
    ap: 4,
    hp: 4,
    traits: ["ZAFT"],
    triggerKeywords: ["When Paired"],
    link: {"kind":"pilotName","values":["Yzak Jule"]},
  },
  "GD01-046": {
    code: "GD01-046",
    structuredSourceText: {
      onSupportUsed: "【During Pair·(Coordinator) Pilot】【Once per Turn】When you use this Unit's <Support> to increase a (ZAFT) Unit's AP, set this Unit as active.",
    },
    nameEn: "Buster Gundam",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 2,
    ap: 1,
    hp: 4,
    traits: ["ZAFT"],
    effectKeywords: ["Support"],
    triggerKeywords: ["Activate·Main"],
    keywordTags: ["Support 3","Support"],
    // "【During Pair･(Coordinator) Pilot】【Once per Turn】When you use this Unit's <Support> to
    // increase a (ZAFT) Unit's AP, set this Unit as active." — Lote 5.
    onSupportUsed: { requiresPairedPilotTrait: "Coordinator", requiresTargetTrait: "ZAFT", oncePerTurn: true },
    link: {"kind":"pilotName","values":["Dearka Elthman"]},
  },
  "GD01-047": {
    code: "GD01-047",
    nameEn: "Shamblo",
    cardType: "UNIT",
    color: "red",
    level: 8,
    cost: 7,
    ap: 6,
    hp: 5,
    traits: ["Zeon"],
    triggerKeywords: ["Attack"],
    link: {"kind":"pilotName","values":["Newtype","Cyber-Newtype"]},
  },
  "GD01-048": {
    code: "GD01-048",
    nameEn: "Zaku I Sniper Type",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 0,
    hp: 1,
    traits: ["Zeon"],
    effectKeywords: ["Support"],
    triggerKeywords: ["Deploy","Activate·Main"],
    keywordTags: ["Support 1"],
    link: {"kind":"pilotName","values":["Zeon"]},
  },
  "GD01-049": {
    code: "GD01-049",
    nameEn: "Blitz Gundam",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["ZAFT"],
    effectKeywords: ["First Strike"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["First Strike"],
    link: {"kind":"pilotName","values":["Nicol Amarfi"]},
  },
  "GD01-050": {
    code: "GD01-050",
    nameEn: "LaGOWE",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["ZAFT"],
    triggerKeywords: ["Attack"],
    link: {"kind":"pilotName","values":["ZAFT"]},
  },
  "GD01-051": {
    code: "GD01-051",
    nameEn: "Kshatriya",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Neo Zeon"],
    link: {"kind":"pilotName","values":["Cyber-Newtype"]},
  },
  "GD01-052": {
    code: "GD01-052",
    nameEn: "Geara Zulu (Guards Type)",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 3,
    ap: 2,
    hp: 4,
    traits: ["Neo Zeon"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-053": {
    code: "GD01-053",
    nameEn: "Geara Doga (Heavy Armed Type)",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 2,
    traits: ["Neo Zeon"],
    triggerKeywords: ["Activate·Main"],
    oncePerTurn: true,
  },
  "GD01-054": {
    code: "GD01-054",
    structuredSourceText: {
      staticAbilities: "While this Unit has 5 or more AP, it gains <Breach 3>.",
    },
    nameEn: "Duel Gundam",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["ZAFT"],
    // "While this Unit has 5 or more AP, it gains <Breach 3>." — Lote 3.
    // Mesmo achado de GD01-019/034: era fixo na Fase 1, corrigido pra
    // condicional (self AP efetivo >= 5).
    staticAbilities: [
      { condition: "always", scope: "self", keyword: "Breach", keywordValue: 3, targetCondition: { kind: "apAtLeast", n: 5 } },
    ],
    link: {"kind":"pilotName","values":["ZAFT"]},
  },
  "GD01-055": {
    code: "GD01-055",
    nameEn: "BuCUE",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["ZAFT"],
    effectKeywords: ["Support"],
    triggerKeywords: ["Activate·Main"],
    keywordTags: ["Support 2"],
  },
  "GD01-056": {
    code: "GD01-056",
    nameEn: "Geara Doga (Sleeves)",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Neo Zeon"],
    triggerKeywords: ["Destroyed"],
  },
  "GD01-057": {
    code: "GD01-057",
    nameEn: "Dreissen (Sleeves)",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Neo Zeon"],
  },
  "GD01-058": {
    code: "GD01-058",
    nameEn: "Galluss-K",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Zeon"],
    triggerKeywords: ["Activate·Action"],
    oncePerTurn: true,
  },
  "GD01-059": {
    code: "GD01-059",
    nameEn: "Zee Zulu",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Neo Zeon"],
    triggerKeywords: ["Attack"],
  },
  "GD01-060": {
    code: "GD01-060",
    nameEn: "Zaku Mariner",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 2,
    traits: ["Zeon"],
  },
  "GD01-061": {
    code: "GD01-061",
    nameEn: "ZuOOT",
    cardType: "UNIT",
    color: "red",
    level: 1,
    cost: 1,
    ap: 0,
    hp: 2,
    traits: ["ZAFT"],
    effectKeywords: ["Support"],
    triggerKeywords: ["Activate·Main"],
    keywordTags: ["Support 1"],
  },
  "GD01-062": {
    code: "GD01-062",
    nameEn: "GOOhN",
    cardType: "UNIT",
    color: "red",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["ZAFT"],
  },
  "GD01-063": {
    code: "GD01-063",
    structuredSourceText: {
      staticAbilities: "During your turn, while this Unit is battling an enemy Unit that is Lv.2 or lower, it gains <First Strike>.",
    },
    nameEn: "ZnO",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 1,
    traits: ["ZAFT"],
    // "During your turn, while this Unit is battling an enemy Unit that is Lv.2 or lower,
    // it gains <First Strike>." — Lote 5. Era effectKeywords/keywordTags fixos na Fase 1
    // (mesmo achado de classe do GD01-108/019/081) — corrigido pra condicional de combate.
    staticAbilities: [
      {
        condition: "always",
        scope: "self",
        keyword: "First Strike",
        duringYourTurnOnly: true,
        boardCondition: { kind: "battlingEnemyLevelAtMost", maxLevel: 2 },
      },
    ],
    link: {"kind":"pilotName","values":["ZAFT"]},
  },
  "GD01-064": {
    code: "GD01-064",
    nameEn: "DINN",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["ZAFT"],
  },
};
