import type { CardDef } from "../../engine/types";

export const UNITS_GREEN: Record<string, CardDef> = {
  "GD01-023": {
    code: "GD01-023",
    nameEn: "Char's Gelgoog",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 4,
    ap: 4,
    hp: 3,
    traits: ["Zeon"],
    triggerKeywords: ["Activate·Main"],
    link: {"kind":"pilotName","values":["Char Aznable"]},
  },
  "GD01-024": {
    code: "GD01-024",
    nameEn: "Wing Gundam Zero",
    cardType: "UNIT",
    color: "green",
    level: 8,
    cost: 8,
    ap: 5,
    hp: 7,
    traits: ["G Team"],
    effectKeywords: ["High-Maneuver"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["High-Maneuver"],
    link: {"kind":"pilotName","values":["Heero Yuy"]},
  },
  "GD01-025": {
    code: "GD01-025",
    nameEn: "Gundam Deathscythe",
    cardType: "UNIT",
    color: "green",
    level: 6,
    cost: 4,
    ap: 5,
    hp: 4,
    traits: ["Operation Meteor"],
    effectKeywords: ["First Strike"],
    keywordTags: ["First Strike"],
    link: {"kind":"pilotName","values":["Duo Maxwell"]},
  },
  "GD01-026": {
    code: "GD01-026",
    nameEn: "Char's Zaku Ⅱ",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Zeon"],
    triggerKeywords: ["Destroyed","During Pair"],
    link: {"kind":"pilotName","values":["Char Aznable"]},
  },
  "GD01-027": {
    code: "GD01-027",
    nameEn: "Big Zam",
    cardType: "UNIT",
    color: "green",
    level: 7,
    cost: 5,
    ap: 5,
    hp: 6,
    traits: ["Zeon"],
    effectKeywords: ["Blocker","Breach"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["Blocker","Breach 4"],
    link: {"kind":"pilotName","values":["Dozle Zabi"]},
  },
  "GD01-028": {
    code: "GD01-028",
    nameEn: "Gundam Sandrock",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 3,
    ap: 4,
    hp: 4,
    traits: ["Operation Meteor"],
    triggerKeywords: ["Deploy"],
    link: {"kind":"pilotName","values":["Quatre Raberba Winner"]},
  },
  "GD01-029": {
    code: "GD01-029",
    nameEn: "Shenlong Gundam",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 4,
    ap: 4,
    hp: 4,
    traits: ["Operation Meteor"],
    effectKeywords: ["Blocker","Breach"],
    triggerKeywords: ["Attack"],
    keywordTags: ["Blocker","Breach 4"],
    link: {"kind":"pilotName","values":["Chang Wufei"]},
  },
  "GD01-030": {
    code: "GD01-030",
    nameEn: "Rick Dom",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Zeon"],
    effectKeywords: ["Breach"],
    keywordTags: ["Breach 2"],
  },
  "GD01-031": {
    code: "GD01-031",
    nameEn: "Gelgoog",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Zeon"],
    link: {"kind":"pilotName","values":["Zeon"]},
  },
  "GD01-032": {
    code: "GD01-032",
    nameEn: "Gyan",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Zeon"],
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["M'Quve"]},
  },
  "GD01-033": {
    code: "GD01-033",
    nameEn: "Gundam Deathscythe",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Operation Meteor"],
    effectKeywords: ["Repair"],
    keywordTags: ["Repair 1"],
    link: {"kind":"pilotName","values":["Duo Maxwell"]},
  },
  "GD01-034": {
    code: "GD01-034",
    nameEn: "Gundam Heavyarms",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Operation Meteor"],
    triggerKeywords: ["During Pair"],
    // "【During Pair】This Unit gains <Breach 3>." — Lote 3. Mesmo achado de
    // GD01-019: era effectKeywords/keywordTags fixos na Fase 1, corrigido pra
    // condicional (só ativo enquanto pareada).
    staticAbilities: [{ condition: "duringPair", scope: "self", keyword: "Breach", keywordValue: 3 }],
    link: {"kind":"pilotName","values":["Trowa Barton"]},
  },
  "GD01-035": {
    code: "GD01-035",
    nameEn: "Zaku Ⅱ",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 2,
    traits: ["Zeon"],
  },
  "GD01-036": {
    code: "GD01-036",
    nameEn: "Gouf",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Zeon"],
  },
  "GD01-037": {
    code: "GD01-037",
    nameEn: "Gogg",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Zeon"],
  },
  "GD01-038": {
    code: "GD01-038",
    nameEn: "Adzam",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 4,
    ap: 2,
    hp: 5,
    traits: ["Zeon"],
    triggerKeywords: ["Deploy"],
    link: {"kind":"pilotName","values":["Zeon"]},
  },
  "GD01-039": {
    code: "GD01-039",
    nameEn: "Dopp",
    cardType: "UNIT",
    color: "green",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Zeon"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-040": {
    code: "GD01-040",
    nameEn: "Wing Gundam",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Operation Meteor"],
    link: {"kind":"pilotName","values":["Heero Yuy"]},
  },
  "GD01-041": {
    code: "GD01-041",
    nameEn: "Shenlong Gundam",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Operation Meteor"],
    effectKeywords: ["Breach"],
    keywordTags: ["Breach 3"],
    link: {"kind":"pilotName","values":["Chang Wufei"]},
  },
  "GD01-042": {
    code: "GD01-042",
    nameEn: "Duo's Leo",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Operation Meteor"],
    link: {"kind":"pilotName","values":["Duo Maxwell"]},
    // "This Unit may choose an active enemy Unit that is Lv.2 or lower as its attack target." — mesmo campo estático de ST02-001 Wing Gundam.
    attackTargetRules: { mayTargetActiveEnemyUnit: { maxLevel: 2 } },
  },
  "GD01-043": {
    code: "GD01-043",
    nameEn: "Rasid's Maganac",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Maganac Corps"],
    triggerKeywords: ["Deploy"],
    link: {"kind":"pilotName","values":["Maganac Corps"]},
  },
};
