import type { CardDef } from "../../engine/types";

export const UNITS_BLUE: Record<string, CardDef> = {
  "GD01-001": {
    code: "GD01-001",
    nameEn: "Gundam",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["Earth Federation","White Base Team"],
    // "All your (White Base Team) Units gain <Repair 1>." — aura contínua e
    // incondicional (scope de grupo + filtro de trait, não bônus só na própria
    // carta; StaticAbility já suporta essa combinação, ver findActiveStaticKeywordAbility).
    staticAbilities: [{ condition: "always", scope: "allFriendlyUnits", keyword: "Repair", keywordValue: 1, targetCondition: { kind: "traitIs", trait: "White Base Team" } }],
    triggerKeywords: ["When Paired"],
    link: {"kind":"pilotName","values":["Amuro Ray"]},
  },
  "GD01-002": {
    code: "GD01-002",
    nameEn: "Unicorn Gundam (Destroy Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 7,
    cost: 6,
    ap: 5,
    hp: 4,
    traits: ["Civilian"],
    triggerKeywords: ["Attack"],
    link: {"kind":"pilotName","values":["Banagher Links"]},
    // "When playing this card from your hand, you may destroy 1 of your Link Units
    // with 'Unicorn Mode' in its card name that is Lv.5. If you do, play this card
    // as if it has 0 Lv. and cost." — Lote 5 (docs/debates 2026-09-13). Validado em
    // deployCard via DeployOptions.sacrificeInstanceId.
    alternateDeploySacrifice: { nameContains: "Unicorn Mode", level: 5 },
  },
  "GD01-003": {
    code: "GD01-003",
    nameEn: "Unicorn Gundam 02 Banshee (Destroy Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 6,
    cost: 4,
    ap: 5,
    hp: 4,
    traits: ["Earth Federation"],
    // "If you do, set this Unit as active. It gains <First Strike> during this turn." — a
    // concessão de First Strike é TEMPORÁRIA e condicional (Lote 5), não uma keyword fixa;
    // effectKeywords/keywordTags incondicionais aqui eram o mesmo achado de dado de classe
    // do GD01-108/019/063/081/091 — removidos (a concessão real vem do EffectSpec).
    triggerKeywords: ["Attack","During Link"],
    link: {"kind":"pilotName","values":["Marida Cruz"]},
  },
  "GD01-004": {
    code: "GD01-004",
    nameEn: "Guncannon",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 3,
    ap: 2,
    hp: 3,
    traits: ["Earth Federation","White Base Team"],
    effectKeywords: ["Repair"],
    triggerKeywords: ["When Paired"],
    keywordTags: ["Repair 1"],
    link: {"kind":"pilotName","values":["White Base Team"]},
  },
  "GD01-005": {
    code: "GD01-005",
    nameEn: "Unicorn Gundam (Unicorn Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 5,
    cost: 4,
    ap: 4,
    hp: 3,
    traits: ["Civilian"],
    triggerKeywords: ["Destroyed","During Link"],
    link: {"kind":"pilotName","values":["Banagher Links"]},
  },
  "GD01-006": {
    code: "GD01-006",
    nameEn: "Delta Plus",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Earth Federation"],
    effectKeywords: ["Repair"],
    triggerKeywords: ["During Link"],
    keywordTags: ["Repair 1"],
    link: {"kind":"pilotName","values":["Earth Federation"]},
    // 【During Link】This Unit gets HP+1. — mesmo mecanismo de ST02-010 Heero Yuy, staticAbilities já cobre.
    staticAbilities: [{ condition: "duringLink", scope: "self", stat: "hp", amount: 1 }],
  },
  "GD01-007": {
    code: "GD01-007",
    nameEn: "Noin's Aries",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 3,
    ap: 2,
    hp: 3,
    traits: ["OZ"],
    triggerKeywords: ["Destroyed"],
    link: {"kind":"pilotName","values":["Lucrezia Noin"]},
  },
  "GD01-008": {
    code: "GD01-008",
    nameEn: "Guntank",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Earth Federation","White Base Team"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-009": {
    code: "GD01-009",
    nameEn: "G-Fighter",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Earth Federation","White Base Team"],
    effectKeywords: ["High-Maneuver"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["High-Maneuver"],
    link: {"kind":"pilotName","values":["White Base Team"]},
  },
  "GD01-010": {
    code: "GD01-010",
    nameEn: "Unicorn Gundam 02 Banshee (Unicorn Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Earth Federation"],
    triggerKeywords: ["When Paired"],
    link: {"kind":"pilotName","values":["Cyber-Newtype"]},
  },
  "GD01-011": {
    code: "GD01-011",
    nameEn: "Loto",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Earth Federation"],
    link: {"kind":"pilotName","values":["Earth Federation"]},
  },
  "GD01-012": {
    code: "GD01-012",
    nameEn: "Zechs' Leo",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["OZ"],
    triggerKeywords: ["When Paired"],
    link: {"kind":"pilotName","values":["OZ"]},
  },
  "GD01-013": {
    code: "GD01-013",
    nameEn: "Gundam",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Earth Federation","White Base Team"],
    link: {"kind":"pilotName","values":["Amuro Ray"]},
  },
  "GD01-014": {
    code: "GD01-014",
    nameEn: "G-Sky Easy",
    cardType: "UNIT",
    color: "blue",
    level: 1,
    cost: 3,
    ap: 1,
    hp: 3,
    traits: ["Earth Federation","White Base Team"],
    triggerKeywords: ["During Link","Activate·Action"],
    link: {"kind":"pilotName","values":["White Base Team"]},
    oncePerTurn: true,
  },
  "GD01-015": {
    code: "GD01-015",
    nameEn: "Ball",
    cardType: "UNIT",
    color: "blue",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Earth Federation"],
    triggerKeywords: ["Attack"],
  },
  "GD01-016": {
    code: "GD01-016",
    nameEn: "Jegan",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 3,
    ap: 2,
    hp: 3,
    traits: ["Earth Federation"],
    // "While you have 2 or more (Earth Federation) Units in play, this card in your hand gets cost -1." — Lote 5.
    dynamicCost: { condition: { kind: "friendlyOtherUnitTraitCountAtLeast", trait: "Earth Federation", n: 2 }, amount: -1 },
  },
  "GD01-017": {
    code: "GD01-017",
    nameEn: "Stark Jegan",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["Earth Federation"],
    effectKeywords: ["Repair"],
    keywordTags: ["Repair 1"],
    link: {"kind":"pilotName","values":["Earth Federation"]},
  },
  "GD01-018": {
    code: "GD01-018",
    nameEn: "ReZEL",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Earth Federation"],
  },
  "GD01-019": {
    code: "GD01-019",
    nameEn: "Byarlant Custom",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Earth Federation"],
    // "While 4 or more enemy Units are in play, this Unit gains <Blocker>." — Lote 3
    // (docs/debates 2026-09-13). Fase 1 tinha isso como effectKeywords/keywordTags
    // FIXOS (bug de mesma classe do achado em GD01-108/Lote 1) — a keyword só existe
    // sob a condição de board, nunca incondicional.
    staticAbilities: [{ condition: "always", scope: "self", keyword: "Blocker", boardCondition: { kind: "enemyUnitCountAtLeast", n: 4 } }],
  },
  "GD01-020": {
    code: "GD01-020",
    nameEn: "Anksha",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["Earth Federation"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-021": {
    code: "GD01-021",
    nameEn: "Pisces",
    cardType: "UNIT",
    color: "blue",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["OZ"],
  },
  "GD01-022": {
    code: "GD01-022",
    nameEn: "Cancer",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["OZ"],
  },
};
