import type { CardDef } from "../../engine/types";

export const UNITS_WHITE: Record<string, CardDef> = {
  "GD01-065": {
    code: "GD01-065",
    nameEn: "Freedom Gundam",
    cardType: "UNIT",
    color: "white",
    level: 7,
    cost: 5,
    ap: 4,
    hp: 6,
    traits: ["Triple Ship Alliance"],
    effectKeywords: ["Blocker"],
    triggerKeywords: ["During Pair"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Kira Yamato"]},
    // "【During Pair】【Once per Turn】When you pair a Pilot with this Unit or one of
    // your white Units, choose 1 enemy Unit. It gets AP-2 during this turn." — Lote 5
    // (docs/debates 2026-09-13). "this Unit or one of your white Units" colapsa pra
    // "a Unit recém-pareada é branca" (esta própria carta já é branca) —
    // requiresPairedUnitColor cobre os 2 casos. Ver EffectSpec "AnyPairing".
    oncePerTurn: true,
    onAnyPairing: { requiresPairedUnitColor: "white" },
  },
  "GD01-066": {
    code: "GD01-066",
    nameEn: "Justice Gundam",
    cardType: "UNIT",
    color: "white",
    level: 7,
    cost: 5,
    ap: 5,
    hp: 5,
    traits: ["Triple Ship Alliance"],
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Deploy","Attack","During Pair"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Athrun Zala"]},
  },
  "GD01-067": {
    code: "GD01-067",
    nameEn: "Gundam Aerial Rebuild",
    cardType: "UNIT",
    color: "white",
    level: 6,
    cost: 5,
    ap: 5,
    hp: 4,
    traits: ["Academy"],
    triggerKeywords: ["When Paired"],
    link: {"kind":"pilotName","values":["Suletta Mercury"]},
  },
  "GD01-068": {
    code: "GD01-068",
    nameEn: "Perfect Strike Gundam",
    cardType: "UNIT",
    color: "white",
    level: 5,
    cost: 3,
    ap: 4,
    hp: 4,
    traits: ["Triple Ship Alliance"],
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Earth Alliance"]},
  },
  "GD01-069": {
    code: "GD01-069",
    nameEn: "Strike Rouge",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Triple Ship Alliance"],
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Activate·Main"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Orb"]},
    oncePerTurn: true,
  },
  "GD01-070": {
    code: "GD01-070",
    nameEn: "Gundam Aerial",
    cardType: "UNIT",
    color: "white",
    level: 5,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["Academy"],
    // "While there are 4 or more Command cards in your trash, this card in your hand gets cost -2." — Lote 5.
    dynamicCost: { condition: { kind: "trashCardTypeCountAtLeast", cardType: "COMMAND", n: 4 }, amount: -2 },
    link: {"kind":"pilotName","values":["Suletta Mercury"]},
  },
  "GD01-071": {
    code: "GD01-071",
    nameEn: "Gundam Pharact",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Academy"],
    triggerKeywords: ["Attack","During Link"],
    link: {"kind":"pilotName","values":["Academy"]},
  },
  "GD01-072": {
    code: "GD01-072",
    nameEn: "Launcher Strike Gundam",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Earth Alliance"],
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Earth Alliance"]},
  },
  "GD01-073": {
    code: "GD01-073",
    nameEn: "Sword Strike Gundam",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Earth Alliance"],
    triggerKeywords: ["Attack","During Link"],
    link: {"kind":"pilotName","values":["Earth Alliance"]},
  },
  "GD01-074": {
    code: "GD01-074",
    nameEn: "Chuchu's Demi Trainer",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 1,
    traits: ["Academy"],
    triggerKeywords: ["Attack"],
    link: {"kind":"pilotName","values":["Chuatury Panlunch"]},
  },
  "GD01-075": {
    code: "GD01-075",
    nameEn: "Darilbalde",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 4,
    hp: 2,
    traits: ["Academy"],
    triggerKeywords: ["Deploy"],
    link: {"kind":"pilotName","values":["Academy"]},
  },
  "GD01-076": {
    code: "GD01-076",
    nameEn: "Michaelis",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Academy"],
    // "While there are 4 or more Command cards in your trash, this Unit gets AP+1 and HP+1." — Lote 3.
    staticAbilities: [
      { condition: "always", scope: "self", stat: "ap", amount: 1, boardCondition: { kind: "trashCardTypeCountAtLeast", cardType: "COMMAND", n: 4 } },
      { condition: "always", scope: "self", stat: "hp", amount: 1, boardCondition: { kind: "trashCardTypeCountAtLeast", cardType: "COMMAND", n: 4 } },
    ],
    link: {"kind":"pilotName","values":["Academy"]},
  },
  "GD01-077": {
    code: "GD01-077",
    nameEn: "Strike Gundam",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Earth Alliance"],
    link: {"kind":"pilotName","values":["Kira Yamato"]},
  },
  "GD01-078": {
    code: "GD01-078",
    nameEn: "Mistral",
    cardType: "UNIT",
    color: "white",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Earth Alliance"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-079": {
    code: "GD01-079",
    nameEn: "Skygrasper",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Earth Alliance"],
    link: {"kind":"pilotName","values":["Earth Alliance"]},
  },
  "GD01-080": {
    code: "GD01-080",
    nameEn: "Cagalli's Skygrasper",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 1,
    traits: ["Earth Alliance"],
    triggerKeywords: ["Destroyed"],
    link: {"kind":"pilotName","values":["Cagalli Yula Athha"]},
  },
  "GD01-081": {
    code: "GD01-081",
    nameEn: "M1 Astray",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Triple Ship Alliance"],
    // "While you have another (Triple Ship Alliance) Unit in play, this Unit gets AP+1 and <Blocker>." — Lote 3.
    // Era effectKeywords/keywordTags fixos na Fase 1 (mesmo achado de GD01-019); "outra" exclui a própria fonte.
    staticAbilities: [
      {
        condition: "always",
        scope: "self",
        stat: "ap",
        amount: 1,
        boardCondition: { kind: "friendlyOtherUnitTraitCountAtLeast", trait: "Triple Ship Alliance", n: 1 },
      },
      {
        condition: "always",
        scope: "self",
        keyword: "Blocker",
        boardCondition: { kind: "friendlyOtherUnitTraitCountAtLeast", trait: "Triple Ship Alliance", n: 1 },
      },
    ],
  },
  "GD01-082": {
    code: "GD01-082",
    nameEn: "Gundam Aerial (Mirasoul Flight Unit)",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Academy"],
    triggerKeywords: ["During Pair","Activate·Action"],
    link: {"kind":"pilotName","values":["Suletta Mercury"]},
    oncePerTurn: true,
  },
  "GD01-083": {
    code: "GD01-083",
    nameEn: "Guel's Dilanza",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Academy"],
    link: {"kind":"pilotName","values":["Academy"]},
  },
  "GD01-084": {
    code: "GD01-084",
    nameEn: "Beguir-Pente",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Academy"],
  },
  "GD01-085": {
    code: "GD01-085",
    nameEn: "Demi Garrison",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 2,
    traits: ["Academy"],
  },
  "GD01-086": {
    code: "GD01-086",
    nameEn: "Gundam Lfrith",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 4,
    traits: ["Vanadis Institute"],
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
  },
};
