import type { EffectSpec, PrimitiveCall } from "../engine/effectSpec";
import type { CardDef } from "../engine/types";
import { EX_RESOURCE_TOKEN } from "../engine/setup";
import { TOKEN_ZAKU_II } from "../fixtures/st03Deck";

// GD01-066 Justice Gundam — token [Fatum-00] gerado pelo 【Deploy】.
export const TOKEN_FATUM_00: CardDef = {
  code: "T-011",
  nameEn: "Fatum-00",
  cardType: "UNIT",
  color: "white",
  ap: 2,
  hp: 2,
  traits: ["Triple Ship Alliance"],
  effectKeywords: ["Blocker"],
  keywordTags: ["Blocker"],
  isToken: true,
};

/**
 * Wave GD01 "Newtype Rising" (Fase 1 - Bootstrap & Ingestão).
 * 
 * Contém o catálogo completo das 130 cartas de GD01 (GD01_CARD_DEFS),
 * as EffectSpecs autoradas com as primitivas existentes no motor,
 * e encaminhamento de mecânicas não suportadas/ambíguas para deferred.ts.
 */

// =============================================================================
// EFFECT SPECS BESPOKE (SUPORTADAS POR PRIMITIVAS EXISTENTES)
// =============================================================================

// GD01-004 Guncannon — 【When Paired】Choose 1 enemy Unit with 2 or less HP. Rest it.
export const GUNCANNON_WHEN_PAIRED: EffectSpec = {
  id: "GD01-004-WhenPaired",
  cardCode: "GD01-004",
  trigger: "When Paired",
  actions: [{ op: "rest", target: { kind: "named", name: "target" } }],
  targetScope: "enemyUnit",
  targetFilter: "hp<=2",
  sourceText: "【When Paired】Choose 1 enemy Unit with 2 or less HP. Rest it.",
};

// GD01-008 Guntank — 【Deploy】Choose 1 rested enemy Unit. Deal 1 damage to it.
export const GUNTANK_DEPLOY: EffectSpec = {
  id: "GD01-008-Deploy",
  cardCode: "GD01-008",
  trigger: "Deploy",
  actions: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 1 }],
  targetScope: "enemyUnit",
  targetFilter: "rested",
  sourceText: "【Deploy】Choose 1 rested enemy Unit. Deal 1 damage to it.",
};

// GD01-010 Unicorn Gundam 02 Banshee (Unicorn Mode) — 【When Paired】Choose 1 enemy Unit with 3 or less HP. Rest it.
export const BANSHEE_UNICORN_WHEN_PAIRED: EffectSpec = {
  id: "GD01-010-WhenPaired",
  cardCode: "GD01-010",
  trigger: "When Paired",
  actions: [{ op: "rest", target: { kind: "named", name: "target" } }],
  targetScope: "enemyUnit",
  targetFilter: "hp<=3",
  sourceText: "【When Paired】Choose 1 enemy Unit with 3 or less HP. Rest it.",
};

// GD01-012 Zechs' Leo — 【When Paired】Choose 1 enemy Unit with 3 or less HP. Rest it.
export const ZECHS_LEO_WHEN_PAIRED: EffectSpec = {
  id: "GD01-012-WhenPaired",
  cardCode: "GD01-012",
  trigger: "When Paired",
  actions: [{ op: "rest", target: { kind: "named", name: "target" } }],
  targetScope: "enemyUnit",
  targetFilter: "hp<=3",
  sourceText: "【When Paired】Choose 1 enemy Unit with 3 or less HP. Rest it.",
};

// GD01-015 Ball — 【Attack】Choose 1 of your Units. It recovers 1 HP.
export const BALL_ATTACK: EffectSpec = {
  id: "GD01-015-Attack",
  cardCode: "GD01-015",
  trigger: "Attack",
  actions: [{ op: "heal", target: { kind: "named", name: "target" }, amount: 1 }],
  targetScope: "friendlyUnit",
  sourceText: "【Attack】Choose 1 of your Units. It recovers 1 HP.",
};

// GD01-074 Chuchu's Demi Trainer — 【Attack】Draw 1. Then, discard 1.
export const CHUCHUS_DEMI_TRAINER_ATTACK: EffectSpec = {
  id: "GD01-074-Attack",
  cardCode: "GD01-074",
  trigger: "Attack",
  actions: [
    { op: "draw", player: "controller", n: 1 },
    { op: "discardNamed", player: "controller", name: "discardTarget", n: 1 },
  ],
  sourceText: "【Attack】Draw 1. Then, discard 1.",
};

// GD01-078 Mistral — 【Deploy】Choose 1 enemy Unit. It gets AP-1 during this turn.
export const MISTRAL_DEPLOY: EffectSpec = {
  id: "GD01-078-Deploy",
  cardCode: "GD01-078",
  trigger: "Deploy",
  actions: [{ op: "modifyStat", target: { kind: "named", name: "target" }, stat: "ap", amount: -1, duration: "endOfTurn" }],
  targetScope: "enemyUnit",
  sourceText: "【Deploy】Choose 1 enemy Unit. It gets AP-1 during this turn.",
};

// GD01-088 Banagher Links — 【When Linked】Draw 1.
export const BANAGHER_LINKS_WHEN_LINKED: EffectSpec = {
  id: "GD01-088-WhenLinked",
  cardCode: "GD01-088",
  trigger: "When Linked",
  actions: [{ op: "draw", player: "controller", n: 1 }],
  sourceText: "【When Linked】Draw 1.",
};

// GD01-099 Intercept Orders — 【Burst】Choose 1 enemy Unit with 5 or less HP. Rest it.
export const INTERCEPT_ORDERS_BURST: EffectSpec = {
  id: "GD01-099-Burst",
  cardCode: "GD01-099",
  trigger: "Burst",
  actions: [{ op: "rest", target: { kind: "named", name: "target" } }],
  targetScope: "enemyUnit",
  targetFilter: "hp<=5",
  sourceText: "【Burst】Choose 1 enemy Unit with 5 or less HP. Rest it.",
};

// GD01-100 A Show of Resolve — 【Main】Draw 2.
export const A_SHOW_OF_RESOLVE_MAIN: EffectSpec = {
  id: "GD01-100-Main",
  cardCode: "GD01-100",
  trigger: "Main",
  actions: [{ op: "draw", player: "controller", n: 2 }],
  sourceText: "【Main】Draw 2.",
};

// GD01-104 Signs of a Revolution — 【Burst】Draw 1.
export const SIGNS_OF_A_REVOLUTION_BURST: EffectSpec = {
  id: "GD01-104-Burst",
  cardCode: "GD01-104",
  trigger: "Burst",
  actions: [{ op: "draw", player: "controller", n: 1 }],
  sourceText: "【Burst】Draw 1.",
};

// GD01-104 Signs of a Revolution — 【Main】Choose 1 rested enemy Unit. Deal 2 damage to it.
export const SIGNS_OF_A_REVOLUTION_MAIN: EffectSpec = {
  id: "GD01-104-Main",
  cardCode: "GD01-104",
  trigger: "Main",
  actions: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 2 }],
  targetScope: "enemyUnit",
  targetFilter: "rested",
  sourceText: "【Main】Choose 1 rested enemy Unit. Deal 2 damage to it.",
};

// GD01-106 Fortress Defense — 【Main】Deploy 2 [Zaku Ⅱ]((Zeon)･AP1･HP1) Unit tokens.
export const FORTRESS_DEFENSE_MAIN: EffectSpec = {
  id: "GD01-106-Main",
  cardCode: "GD01-106",
  trigger: "Main",
  actions: [{ op: "spawnToken", def: TOKEN_ZAKU_II, player: "controller", zone: "battleArea", count: 2 }],
  sourceText: "【Main】Deploy 2 [Zaku Ⅱ]((Zeon)･AP1･HP1) Unit tokens.",
};

// GD01-107 First Contact — 【Burst】Place 1 EX Resource.
export const FIRST_CONTACT_BURST: EffectSpec = {
  id: "GD01-107-Burst",
  cardCode: "GD01-107",
  trigger: "Burst",
  actions: [{ op: "spawnToken", def: EX_RESOURCE_TOKEN, player: "controller", zone: "resourceArea" }],
  sourceText: "【Burst】Place 1 EX Resource.",
};

// GD01-107 First Contact — 【Main】Place 1 rested Resource.
export const FIRST_CONTACT_MAIN: EffectSpec = {
  id: "GD01-107-Main",
  cardCode: "GD01-107",
  trigger: "Main",
  actions: [{ op: "spawnToken", def: EX_RESOURCE_TOKEN, player: "controller", zone: "resourceArea", rested: true }],
  sourceText: "【Main】Place 1 rested Resource.",
};

// GD01-111 Battle of Aces — 【Burst】Choose 1 enemy Unit. Deal 2 damage to it.
export const BATTLE_OF_ACES_BURST: EffectSpec = {
  id: "GD01-111-Burst",
  cardCode: "GD01-111",
  trigger: "Burst",
  actions: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 2 }],
  targetScope: "enemyUnit",
  sourceText: "【Burst】Choose 1 enemy Unit. Deal 2 damage to it.",
};

// GD01-115 Zeon Remnant Forces — 【Main】Choose 1 enemy Unit. Deal 1 damage to it.
export const ZEON_REMNANT_FORCES_MAIN: EffectSpec = {
  id: "GD01-115-Main",
  cardCode: "GD01-115",
  trigger: "Main",
  actions: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 1 }],
  targetScope: "enemyUnit",
  sourceText: "【Main】Choose 1 enemy Unit. Deal 1 damage to it.",
};

// GD01-118 Overflowing Affection — 【Main】Draw 2. Then, discard 1.
export const OVERFLOWING_AFFECTION_MAIN: EffectSpec = {
  id: "GD01-118-Main",
  cardCode: "GD01-118",
  trigger: "Main",
  actions: [
    { op: "draw", player: "controller", n: 2 },
    { op: "discardNamed", player: "controller", name: "discardTarget", n: 1 },
  ],
  sourceText: "【Main】Draw 2. Then, discard 1.",
};

// GD01-120 Naval Bombardment — 【Burst】Choose 1 enemy Unit. It gets AP-3 during this turn.
export const NAVAL_BOMBARDMENT_BURST: EffectSpec = {
  id: "GD01-120-Burst",
  cardCode: "GD01-120",
  trigger: "Burst",
  actions: [{ op: "modifyStat", target: { kind: "named", name: "target" }, stat: "ap", amount: -3, duration: "endOfTurn" }],
  targetScope: "enemyUnit",
  sourceText: "【Burst】Choose 1 enemy Unit. It gets AP-3 during this turn.",
};

// GD01-121 Midair Modifications — 【Main】Choose 1 rested Unit with <Blocker>. Set it as active. It can't attack during this turn.
export const MIDAIR_MODIFICATIONS_MAIN: EffectSpec = {
  id: "GD01-121-Main",
  cardCode: "GD01-121",
  trigger: "Main",
  actions: [
    { op: "setActive", target: { kind: "named", name: "target" } },
    { op: "preventAttackThisTurn", target: { kind: "named", name: "target" } },
  ],
  targetScope: "friendlyUnit",
  sourceText: "【Main】Choose 1 rested Unit with <Blocker>. Set it as active. It can't attack during this turn.",
};

// GD01-124 Side 7 — 【Burst】Deploy this card.
export const SIDE_7_BURST: EffectSpec = {
  id: "GD01-124-Burst",
  cardCode: "GD01-124",
  trigger: "Burst",
  actions: [{ op: "deployThisCard" }],
  sourceText: "【Burst】Deploy this card.",
};

// GD01-124 Side 7 — 【Deploy】Add 1 of your Shields to your hand.
export const SIDE_7_DEPLOY: EffectSpec = {
  id: "GD01-124-Deploy",
  cardCode: "GD01-124",
  trigger: "Deploy",
  actions: [{ op: "addShieldToHand", player: "controller", count: 1 }],
  sourceText: "【Deploy】Add 1 of your Shields to your hand.",
};

// GD01-124 Side 7 — 【Activate･Main】Rest this Base：Choose 1 friendly Unit. It recovers 1 HP.
export const SIDE_7_ACTIVATE_MAIN: EffectSpec = {
  id: "GD01-124-ActivateMain",
  cardCode: "GD01-124",
  trigger: "Activate·Main",
  cost: [{ op: "rest", target: { kind: "self" } }],
  actions: [{ op: "heal", target: { kind: "named", name: "target" }, amount: 1 }],
  targetScope: "friendlyUnit",
  sourceText: "【Activate･Main】Rest this Base：Choose 1 friendly Unit. It recovers 1 HP.",
};

// GD01-126 Underground Desert Base — 【Burst】Deploy this card.
export const UNDERGROUND_DESERT_BASE_BURST: EffectSpec = {
  id: "GD01-126-Burst",
  cardCode: "GD01-126",
  trigger: "Burst",
  actions: [{ op: "deployThisCard" }],
  sourceText: "【Burst】Deploy this card.",
};

// GD01-126 Underground Desert Base — 【Deploy】Add 1 of your Shields to your hand.
export const UNDERGROUND_DESERT_BASE_DEPLOY: EffectSpec = {
  id: "GD01-126-Deploy",
  cardCode: "GD01-126",
  trigger: "Deploy",
  actions: [{ op: "addShieldToHand", player: "controller", count: 1 }],
  sourceText: "【Deploy】Add 1 of your Shields to your hand.",
};

// GD01-128 Mining Asteroid Palau — 【Burst】Deploy this card.
export const MINING_ASTEROID_PALAU_BURST: EffectSpec = {
  id: "GD01-128-Burst",
  cardCode: "GD01-128",
  trigger: "Burst",
  actions: [{ op: "deployThisCard" }],
  sourceText: "【Burst】Deploy this card.",
};

// GD01-128 Mining Asteroid Palau — 【Deploy】Add 1 of your Shields to your hand.
export const MINING_ASTEROID_PALAU_DEPLOY: EffectSpec = {
  id: "GD01-128-Deploy",
  cardCode: "GD01-128",
  trigger: "Deploy",
  actions: [{ op: "addShieldToHand", player: "controller", count: 1 }],
  sourceText: "【Deploy】Add 1 of your Shields to your hand.",
};

// GD01-001 Gundam — 【When Paired】If you have 2 or more other Units in play, draw 1.
// (a outra cláusula do texto oficial, "All your (White Base Team) Units gain
// <Repair 1>", segue deferida em deferred.ts — aura de concessão de keyword
// em grupo, fora do escopo desta resolução.)
export const GUNDAM_WHEN_PAIRED: EffectSpec = {
  id: "GD01-001-WhenPaired",
  cardCode: "GD01-001",
  trigger: "When Paired",
  condition: { predicate: "controllerOtherUnitCountAtLeast:2", then: [{ op: "draw", player: "controller", n: 1 }] },
  actions: [],
  sourceText: "【When Paired】If you have 2 or more other Units in play, draw 1.",
};

// GD01-038 Adzam — 【Deploy】If 5 or more enemy Units are in play, deal 1 damage to all enemy Units.
export const ADZAM_DEPLOY: EffectSpec = {
  id: "GD01-038-Deploy",
  cardCode: "GD01-038",
  trigger: "Deploy",
  condition: {
    predicate: "enemyUnitCountAtLeast:5",
    then: [{ op: "damageUnit", target: { kind: "group", group: { kind: "allEnemyUnits" } }, amount: 1 }],
  },
  actions: [],
  sourceText: "【Deploy】If 5 or more enemy Units are in play, deal 1 damage to all enemy Units.",
};

// GD01-049 Blitz Gundam — 【Deploy】Choose 1 of your (ZAFT) Units with 5 or more AP. It gains <First Strike> during this turn.
export const BLITZ_GUNDAM_DEPLOY: EffectSpec = {
  id: "GD01-049-Deploy",
  cardCode: "GD01-049",
  trigger: "Deploy",
  actions: [{ op: "grantKeyword", target: { kind: "named", name: "target" }, keyword: "First Strike", duration: "endOfTurn" }],
  targetScope: "friendlyUnit",
  targetFilter: "trait:ZAFT;ap>=5",
  sourceText: "【Deploy】Choose 1 of your (ZAFT) Units with 5 or more AP. It gains <First Strike> during this turn.",
};

// GD01-052 Geara Zulu (Guards Type) — 【Deploy】Choose 1 enemy Unit. Deal 1 damage to it.
export const GEARA_ZULU_DEPLOY: EffectSpec = {
  id: "GD01-052-Deploy",
  cardCode: "GD01-052",
  trigger: "Deploy",
  actions: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 1 }],
  targetScope: "enemyUnit",
  sourceText: "【Deploy】Choose 1 enemy Unit. Deal 1 damage to it.",
};

// GD01-053 Geara Doga (Heavy Armed Type) — 【Activate･Main】【Once per Turn】①：Choose 1 enemy Unit with 2 or less AP. Deal 1 damage to it.
export const GEARA_DOGA_HEAVY_ARMED_ACTIVATE_MAIN: EffectSpec = {
  id: "GD01-053-ActivateMain",
  cardCode: "GD01-053",
  trigger: "Activate·Main",
  actions: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 1 }],
  targetScope: "enemyUnit",
  targetFilter: "ap<=2",
  sourceText: "【Activate･Main】【Once per Turn】①：Choose 1 enemy Unit with 2 or less AP. Deal 1 damage to it.",
};

// GD01-056 Geara Doga (Sleeves) — 【Destroyed】Choose 1 enemy Unit with 5 or less AP. Deal 1 damage to it.
export const GEARA_DOGA_SLEEVES_DESTROYED: EffectSpec = {
  id: "GD01-056-Destroyed",
  cardCode: "GD01-056",
  trigger: "Destroyed",
  actions: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 1 }],
  targetScope: "enemyUnit",
  targetFilter: "ap<=5",
  sourceText: "【Destroyed】Choose 1 enemy Unit with 5 or less AP. Deal 1 damage to it.",
};

// GD01-068 Perfect Strike Gundam — 【Deploy】Choose 1 enemy Unit with 1 HP. Return it to its owner's hand.
export const PERFECT_STRIKE_GUNDAM_DEPLOY: EffectSpec = {
  id: "GD01-068-Deploy",
  cardCode: "GD01-068",
  trigger: "Deploy",
  actions: [{ op: "moveZone", target: { kind: "named", name: "target" }, toZone: "hand" }],
  targetScope: "enemyUnit",
  targetFilter: "hp<=1",
  sourceText: "【Deploy】Choose 1 enemy Unit with 1 HP. Return it to its owner's hand.",
};

// GD01-073 Sword Strike Gundam — 【During Link】【Attack】Choose 1 enemy Unit with 2 or less HP. Return it to its owner's hand.
export const SWORD_STRIKE_GUNDAM_ATTACK: EffectSpec = {
  id: "GD01-073-Attack",
  cardCode: "GD01-073",
  trigger: "Attack",
  condition: {
    predicate: "selfIsLinkUnit",
    then: [{ op: "moveZone", target: { kind: "named", name: "target" }, toZone: "hand" }],
  },
  actions: [],
  targetScope: "enemyUnit",
  targetFilter: "hp<=2",
  sourceText: "【During Link】【Attack】Choose 1 enemy Unit with 2 or less HP. Return it to its owner's hand.",
};

// GD01-071 Gundam Pharact — 【During Link】【Attack】Choose 1 enemy Unit. It gets AP-2 during this battle.
export const GUNDAM_PHARACT_ATTACK: EffectSpec = {
  id: "GD01-071-Attack",
  cardCode: "GD01-071",
  trigger: "Attack",
  condition: {
    predicate: "selfIsLinkUnit",
    then: [{ op: "modifyStat", target: { kind: "named", name: "target" }, stat: "ap", amount: -2, duration: "thisBattle" }],
  },
  actions: [],
  targetScope: "enemyUnit",
  sourceText: "【During Link】【Attack】Choose 1 enemy Unit. It gets AP-2 during this battle.",
};

// GD01-075 Darilbalde — 【Deploy】Choose 1 enemy Unit with 1 HP. Return it to its owner's hand.
export const DARILBALDE_DEPLOY: EffectSpec = {
  id: "GD01-075-Deploy",
  cardCode: "GD01-075",
  trigger: "Deploy",
  actions: [{ op: "moveZone", target: { kind: "named", name: "target" }, toZone: "hand" }],
  targetScope: "enemyUnit",
  targetFilter: "hp<=1",
  sourceText: "【Deploy】Choose 1 enemy Unit with 1 HP. Return it to its owner's hand.",
};

// GD01-080 Cagalli's Skygrasper — 【Destroyed】Choose 1 enemy Unit that is Lv.2 or lower. Return it to its owner's hand.
export const CAGALLIS_SKYGRASPER_DESTROYED: EffectSpec = {
  id: "GD01-080-Destroyed",
  cardCode: "GD01-080",
  trigger: "Destroyed",
  actions: [{ op: "moveZone", target: { kind: "named", name: "target" }, toZone: "hand" }],
  targetScope: "enemyUnit",
  targetFilter: "level<=2",
  sourceText: "【Destroyed】Choose 1 enemy Unit that is Lv.2 or lower. Return it to its owner's hand.",
};

// GD01-116 Stealth Stratagem — 【Main】/【Action】Choose 1 enemy Unit with 2 or less AP. Deal 2 damage to it.
// (lado 【Pilot】[Nicol Amarfi] é modo alternativo, fora do escopo desta resolução — ver pilotMode.)
export const STEALTH_STRATAGEM_MAIN: EffectSpec = {
  id: "GD01-116-Main",
  cardCode: "GD01-116",
  trigger: "Main",
  actions: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 2 }],
  targetScope: "enemyUnit",
  targetFilter: "ap<=2",
  sourceText: "【Main】/【Action】Choose 1 enemy Unit with 2 or less AP. Deal 2 damage to it.",
};
export const STEALTH_STRATAGEM_ACTION: EffectSpec = { ...STEALTH_STRATAGEM_MAIN, id: "GD01-116-Action", trigger: "Action" };

// GD01-117 The Witch and the Bride — 【Burst】Activate this card's 【Main】. / 【Main】/【Action】
// Choose 1 enemy Unit with 5 or less HP. Return it to its owner's hand.
const WITCH_AND_BRIDE_ACTIONS: PrimitiveCall[] = [{ op: "moveZone", target: { kind: "named", name: "target" }, toZone: "hand" }];
export const WITCH_AND_BRIDE_BURST: EffectSpec = {
  id: "GD01-117-Burst",
  cardCode: "GD01-117",
  trigger: "Burst",
  actions: WITCH_AND_BRIDE_ACTIONS,
  targetScope: "enemyUnit",
  targetFilter: "hp<=5",
  sourceText: "【Burst】Activate this card's 【Main】.",
};
export const WITCH_AND_BRIDE_MAIN: EffectSpec = { ...WITCH_AND_BRIDE_BURST, id: "GD01-117-Main", trigger: "Main", sourceText: "【Main】/【Action】Choose 1 enemy Unit with 5 or less HP. Return it to its owner's hand." };
export const WITCH_AND_BRIDE_ACTION: EffectSpec = { ...WITCH_AND_BRIDE_MAIN, id: "GD01-117-Action", trigger: "Action" };

// GD01-129 Kusanagi — 【Deploy】Add 1 of your Shields to your hand. Then, choose 1 enemy Unit with 3 or less HP. Return it to its owner's hand.
export const KUSANAGI_DEPLOY: EffectSpec = {
  id: "GD01-129-Deploy",
  cardCode: "GD01-129",
  trigger: "Deploy",
  actions: [
    { op: "addShieldToHand", player: "controller", count: 1 },
    { op: "moveZone", target: { kind: "named", name: "target" }, toZone: "hand" },
  ],
  targetScope: "enemyUnit",
  targetFilter: "hp<=3",
  sourceText: "【Deploy】Add 1 of your Shields to your hand. Then, choose 1 enemy Unit with 3 or less HP. Return it to its owner's hand.",
};

// GD01-007 Noin's Aries — 【Destroyed】If you have another (OZ) Unit in play, draw 1.
export const NOINS_ARIES_DESTROYED: EffectSpec = {
  id: "GD01-007-Destroyed",
  cardCode: "GD01-007",
  trigger: "Destroyed",
  condition: { predicate: "controllerOtherUnitWithTrait:OZ", then: [{ op: "draw", player: "controller", n: 1 }] },
  actions: [],
  sourceText: "【Destroyed】If you have another (OZ) Unit in play, draw 1.",
};

// GD01-009 G-Fighter — 【Deploy】Choose 1 of your (White Base Team) Units. It gains <High-Maneuver> during this turn.
export const G_FIGHTER_DEPLOY: EffectSpec = {
  id: "GD01-009-Deploy",
  cardCode: "GD01-009",
  trigger: "Deploy",
  actions: [{ op: "grantKeyword", target: { kind: "named", name: "target" }, keyword: "High-Maneuver", duration: "endOfTurn" }],
  targetScope: "friendlyUnit",
  targetFilter: "trait:White Base Team",
  sourceText: "【Deploy】Choose 1 of your (White Base Team) Units. It gains <High-Maneuver> during this turn.",
};

// GD01-020 Anksha — 【Deploy】Choose 1 rested enemy Unit. Deal 1 damage to it.
export const ANKSHA_DEPLOY: EffectSpec = {
  id: "GD01-020-Deploy",
  cardCode: "GD01-020",
  trigger: "Deploy",
  actions: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 1 }],
  targetScope: "enemyUnit",
  targetFilter: "rested",
  sourceText: "【Deploy】Choose 1 rested enemy Unit. Deal 1 damage to it.",
};

// GD01-028 Gundam Sandrock — 【Deploy】You may deploy 1 (Maganac Corps) Unit card from your hand.
export const GUNDAM_SANDROCK_DEPLOY: EffectSpec = {
  id: "GD01-028-Deploy",
  cardCode: "GD01-028",
  trigger: "Deploy",
  actions: [{ op: "deployFromHandTriggered", player: "controller", filter: { cardType: "UNIT", anyTrait: ["Maganac Corps"] } }],
  optional: true,
  sourceText: "【Deploy】You may deploy 1 (Maganac Corps) Unit card from your hand.",
};

// GD01-029 Shenlong Gundam — 【Attack】Choose 1 enemy Unit with <Blocker> that is Lv.3 or lower. Destroy it.
export const SHENLONG_GUNDAM_ATTACK: EffectSpec = {
  id: "GD01-029-Attack",
  cardCode: "GD01-029",
  trigger: "Attack",
  actions: [{ op: "destroy", target: { kind: "named", name: "target" } }],
  targetScope: "enemyUnit",
  targetFilter: "hasKeyword:Blocker;level<=3",
  sourceText: "【Attack】Choose 1 enemy Unit with <Blocker> that is Lv.3 or lower. Destroy it.",
};

// GD01-032 Gyan — 【When Paired･(Zeon) Pilot】Choose 1 enemy Unit with <Blocker> that is Lv.2 or lower. Destroy it.
export const GYAN_WHEN_PAIRED: EffectSpec = {
  id: "GD01-032-WhenPaired",
  cardCode: "GD01-032",
  trigger: "When Paired",
  condition: {
    predicate: "pairedPilotHasTrait:Zeon",
    then: [{ op: "destroy", target: { kind: "named", name: "target" } }],
  },
  actions: [],
  targetScope: "enemyUnit",
  targetFilter: "hasKeyword:Blocker;level<=2",
  sourceText: "【When Paired･(Zeon) Pilot】Choose 1 enemy Unit with <Blocker> that is Lv.2 or lower. Destroy it.",
};

// GD01-025 Gundam Deathscythe — 【When Paired･(Operation Meteor) Pilot】Place 1 rested Resource. Then, this Unit gains <First Strike> during this turn.
export const GUNDAM_DEATHSCYTHE_WHEN_PAIRED: EffectSpec = {
  id: "GD01-025-WhenPaired",
  cardCode: "GD01-025",
  trigger: "When Paired",
  condition: {
    predicate: "pairedPilotHasTrait:Operation Meteor",
    then: [
      { op: "spawnToken", def: EX_RESOURCE_TOKEN, player: "controller", zone: "resourceArea", rested: true },
      { op: "grantKeyword", target: { kind: "self" }, keyword: "First Strike", duration: "endOfTurn" },
    ],
  },
  actions: [],
  sourceText: "【When Paired･(Operation Meteor) Pilot】Place 1 rested Resource. Then, this Unit gains <First Strike> during this turn.",
};

// GD01-026 Char's Zaku Ⅱ — 【During Pair】【Destroyed】Deploy 1 rested [Char's Zaku Ⅱ]((Zeon)･AP3･HP1) Unit token.
export const CHARS_ZAKU_II_DESTROYED: EffectSpec = {
  id: "GD01-026-Destroyed",
  cardCode: "GD01-026",
  trigger: "Destroyed",
  duringPair: true,
  actions: [{ op: "spawnToken", def: TOKEN_ZAKU_II, player: "controller", zone: "battleArea", rested: true }],
  sourceText: "【During Pair】【Destroyed】Deploy 1 rested [Char's Zaku Ⅱ]((Zeon)･AP3･HP1) Unit token.",
};

// GD01-050 LaGOWE — 【Attack】If this Unit has 5 or more AP and it is attacking an enemy Unit, choose 1 enemy Unit. Deal 2 damage to it.
export const LAGOWE_ATTACK: EffectSpec = {
  id: "GD01-050-Attack",
  cardCode: "GD01-050",
  trigger: "Attack",
  condition: {
    predicate: "selfApAtLeast:5;attackingEnemyUnit",
    then: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 2 }],
  },
  actions: [],
  targetScope: "enemyUnit",
  sourceText: "【Attack】If this Unit has 5 or more AP and it is attacking an enemy Unit, choose 1 enemy Unit. Deal 2 damage to it.",
};

// GD01-059 Zee Zulu — 【Attack】If you are attacking the enemy player, this Unit gets AP+2 during this battle.
export const ZEE_ZULU_ATTACK: EffectSpec = {
  id: "GD01-059-Attack",
  cardCode: "GD01-059",
  trigger: "Attack",
  condition: {
    predicate: "attackingPlayer",
    then: [{ op: "modifyStat", target: { kind: "self" }, stat: "ap", amount: 2, duration: "thisBattle" }],
  },
  actions: [],
  sourceText: "【Attack】If you are attacking the enemy player, this Unit gets AP+2 during this battle.",
};

// GD01-066 Justice Gundam — 【Deploy】Deploy 1 [Fatum-00]((Triple Ship Alliance)･AP2･HP2･<Blocker>) Unit token.
// (a 2ª cláusula oficial, "【During Pair】【Attack】Choose 1 of your (Triple Ship
// Alliance) Unit tokens. It may attack on the turn it is deployed.", segue
// deferida em deferred.ts — concessão de "pode atacar no turno em que foi
// deployada" fora da exceção nativa de Link Unit, fora do escopo desta resolução.)
export const JUSTICE_GUNDAM_DEPLOY: EffectSpec = {
  id: "GD01-066-Deploy",
  cardCode: "GD01-066",
  trigger: "Deploy",
  actions: [{ op: "spawnToken", def: TOKEN_FATUM_00, player: "controller", zone: "battleArea" }],
  sourceText: "【Deploy】Deploy 1 [Fatum-00]((Triple Ship Alliance)･AP2･HP2･<Blocker>) Unit token.",
};

// GD01-047 Shamblo — 【Attack】If 2 or more other rested friendly Units are in play, choose 1 enemy Unit. Deal 3 damage to it.
export const SHAMBLO_ATTACK: EffectSpec = {
  id: "GD01-047-Attack",
  cardCode: "GD01-047",
  trigger: "Attack",
  condition: {
    predicate: "controllerOtherRestedUnitCountAtLeast:2",
    then: [{ op: "damageUnit", target: { kind: "named", name: "target" }, amount: 3 }],
  },
  actions: [],
  targetScope: "enemyUnit",
  sourceText: "【Attack】If 2 or more other rested friendly Units are in play, choose 1 enemy Unit. Deal 3 damage to it.",
};

// GD01-097 Guel Jeturk — 【Activate･Main】【Once per Turn】If your opponent has 8 or more cards in their hand, set this Unit as active. It can't attack during this turn.
export const GUEL_JETURK_ACTIVATE_MAIN: EffectSpec = {
  id: "GD01-097-ActivateMain",
  cardCode: "GD01-097",
  trigger: "Activate·Main",
  condition: {
    predicate: "opponentHandCountAtLeast:8",
    then: [{ op: "setActive", target: { kind: "self" } }, { op: "preventAttackThisTurn", target: { kind: "self" } }],
  },
  actions: [],
  sourceText: "【Activate･Main】【Once per Turn】If your opponent has 8 or more cards in their hand, set this Unit as active. It can't attack during this turn.",
};

// GD01-098 Elan Ceres — 【Activate･Action】【Once per Turn】If an enemy Unit with 1 or less AP is in play, this Unit recovers 1 HP.
export const ELAN_CERES_ACTIVATE_ACTION: EffectSpec = {
  id: "GD01-098-ActivateAction",
  cardCode: "GD01-098",
  trigger: "Activate·Action",
  condition: {
    predicate: "enemyUnitExistsWithApAtMost:1",
    then: [{ op: "heal", target: { kind: "self" }, amount: 1 }],
  },
  actions: [],
  sourceText: "【Activate･Action】【Once per Turn】If an enemy Unit with 1 or less AP is in play, this Unit recovers 1 HP.",
};

// GD01-069 Strike Rouge — 【Activate･Main】【Once per Turn】①：Choose 1 of your rested white Units with <Blocker>. Set it as active. It can't attack during this turn.
export const STRIKE_ROUGE_ACTIVATE_MAIN: EffectSpec = {
  id: "GD01-069-ActivateMain",
  cardCode: "GD01-069",
  trigger: "Activate·Main",
  actions: [
    { op: "setActive", target: { kind: "named", name: "target" } },
    { op: "preventAttackThisTurn", target: { kind: "named", name: "target" } },
  ],
  targetScope: "friendlyUnit",
  targetFilter: "color:white;hasKeyword:Blocker;rested",
  sourceText: "【Activate･Main】【Once per Turn】①：Choose 1 of your rested white Units with <Blocker>. Set it as active. It can't attack during this turn.",
};

// GD01-082 Gundam Aerial (Mirasoul Flight Unit) — 【During Pair】【Activate･Action】【Once per Turn】②：Choose 1 enemy Unit. It gets AP-1 during this battle.
export const GUNDAM_AERIAL_MIRASOUL_ACTIVATE_ACTION: EffectSpec = {
  id: "GD01-082-ActivateAction",
  cardCode: "GD01-082",
  trigger: "Activate·Action",
  condition: {
    predicate: "selfIsPaired",
    then: [{ op: "modifyStat", target: { kind: "named", name: "target" }, stat: "ap", amount: -1, duration: "thisBattle" }],
  },
  actions: [],
  targetScope: "enemyUnit",
  sourceText: "【During Pair】【Activate･Action】【Once per Turn】②：Choose 1 enemy Unit. It gets AP-1 during this battle.",
};

// GD01-105 Citizens, Take a Stand! — 【Main】All your Units get AP+2 during this turn.
export const CITIZENS_TAKE_A_STAND_MAIN: EffectSpec = {
  id: "GD01-105-Main",
  cardCode: "GD01-105",
  trigger: "Main",
  actions: [{ op: "modifyStat", target: { kind: "group", group: { kind: "allFriendlyUnits" } }, stat: "ap", amount: 2, duration: "endOfTurn" }],
  sourceText: "【Main】All your Units get AP+2 during this turn.",
};

// ─────────────────────────────────────────────────────────────────────────
// Lote 1 de gaps de motor fechado (docs/debates 2026-09-13) — TargetScope
// "anyUnit" e TargetGroup "allUnits" (texto oficial "Choose 1 Unit"/"all
// Units" sem "enemy"/"friendly" — os 2 lados do tabuleiro).
// ─────────────────────────────────────────────────────────────────────────

// GD01-014 G-Sky Easy — 【During Link】【Activate･Action】【Once per Turn】Choose 1 Unit. It recovers 1 HP.
export const G_SKY_EASY_ACTIVATE_ACTION: EffectSpec = {
  id: "GD01-014-ActivateAction",
  cardCode: "GD01-014",
  trigger: "Activate·Action",
  condition: {
    predicate: "selfIsLinkUnit",
    then: [{ op: "heal", target: { kind: "named", name: "target" }, amount: 1 }],
  },
  actions: [],
  targetScope: "anyUnit",
  sourceText: "【During Link】【Activate･Action】【Once per Turn】Choose 1 Unit. It recovers 1 HP.",
};

// GD01-024 Wing Gundam Zero — 【Deploy】Deal 3 damage to all Units that are Lv.5 or lower.
export const WING_GUNDAM_ZERO_DEPLOY: EffectSpec = {
  id: "GD01-024-Deploy",
  cardCode: "GD01-024",
  trigger: "Deploy",
  actions: [{ op: "damageUnit", target: { kind: "group", group: { kind: "allUnits", maxLevel: 5 } }, amount: 3 }],
  sourceText: "【Deploy】Deal 3 damage to all Units that are Lv.5 or lower.",
};

// GD01-027 Big Zam — 【Deploy】If there are 10 or more (Zeon)/(Neo Zeon) Unit cards in your trash, deal 4 damage to all Units with <Blocker>.
export const BIG_ZAM_DEPLOY: EffectSpec = {
  id: "GD01-027-Deploy",
  cardCode: "GD01-027",
  trigger: "Deploy",
  condition: {
    predicate: "controllerTrashUnitCountWithAnyTraitAtLeast:Zeon,Neo Zeon:10",
    then: [{ op: "damageUnit", target: { kind: "group", group: { kind: "allUnits", hasKeyword: "Blocker" } }, amount: 4 }],
  },
  actions: [],
  sourceText: "【Deploy】If there are 10 or more (Zeon)/(Neo Zeon) Unit cards in your trash, deal 4 damage to all Units with <Blocker>.",
};

// GD01-058 Galluss-K — 【Activate･Action】【Once per Turn】①：Choose 1 Unit that is Lv.4 or higher. It gets AP+1 during this battle.
export const GALLUSS_K_ACTIVATE_ACTION: EffectSpec = {
  id: "GD01-058-ActivateAction",
  cardCode: "GD01-058",
  trigger: "Activate·Action",
  cost: [{ op: "payResourceCost", player: "controller", n: 1 }],
  actions: [{ op: "modifyStat", target: { kind: "named", name: "target" }, stat: "ap", amount: 1, duration: "thisBattle" }],
  targetScope: "anyUnit",
  targetFilter: "level>=4",
  sourceText: "【Activate･Action】【Once per Turn】①：Choose 1 Unit that is Lv.4 or higher. It gets AP+1 during this battle.",
};

// GD01-108 Strategic Arms — 【Main】Deal 2 damage to all Units with <Blocker>.
export const STRATEGIC_ARMS_MAIN: EffectSpec = {
  id: "GD01-108-Main",
  cardCode: "GD01-108",
  trigger: "Main",
  actions: [{ op: "damageUnit", target: { kind: "group", group: { kind: "allUnits", hasKeyword: "Blocker" } }, amount: 2 }],
  sourceText: "【Main】Deal 2 damage to all Units with <Blocker>.",
};

// GD01-110 Rasid's Orders — 【Main】/【Action】Choose 1 Unit that is Lv.4 or higher. During this turn, it may choose an active enemy Unit with 6 or less AP as its attack target.
const RASIDS_ORDERS_ACTIONS: PrimitiveCall[] = [
  { op: "grantAttackTargetRelax", target: { kind: "named", name: "target" }, maxAp: 6 },
];
export const RASIDS_ORDERS_MAIN: EffectSpec = {
  id: "GD01-110-Main",
  cardCode: "GD01-110",
  trigger: "Main",
  actions: RASIDS_ORDERS_ACTIONS,
  targetScope: "anyUnit",
  targetFilter: "level>=4",
  sourceText: "【Main】/【Action】Choose 1 Unit that is Lv.4 or higher. During this turn, it may choose an active enemy Unit with 6 or less AP as its attack target.",
};
export const RASIDS_ORDERS_ACTION: EffectSpec = {
  id: "GD01-110-Action",
  cardCode: "GD01-110",
  trigger: "Action",
  actions: RASIDS_ORDERS_ACTIONS,
  targetScope: "anyUnit",
  targetFilter: "level>=4",
  sourceText: "【Main】/【Action】Choose 1 Unit that is Lv.4 or higher. During this turn, it may choose an active enemy Unit with 6 or less AP as its attack target.",
};

// GD01-101 Deep Devotion — 【Main】/【Action】Choose 1 friendly Link Unit. It recovers 3 HP.
export const DEEP_DEVOTION_MAIN: EffectSpec = {
  id: "GD01-101-Main",
  cardCode: "GD01-101",
  trigger: "Main",
  actions: [{ op: "heal", target: { kind: "named", name: "target" }, amount: 3 }],
  targetScope: "friendlyUnit",
  targetFilter: "linkUnit",
  sourceText: "【Main】/【Action】Choose 1 friendly Link Unit. It recovers 3 HP.",
};
export const DEEP_DEVOTION_ACTION: EffectSpec = { ...DEEP_DEVOTION_MAIN, id: "GD01-101-Action", trigger: "Action" };

// GD01-102 Securing the Supply Line — 【Main】All friendly Units that are Lv.4 or lower recover 2 HP.
export const SECURING_THE_SUPPLY_LINE_MAIN: EffectSpec = {
  id: "GD01-102-Main",
  cardCode: "GD01-102",
  trigger: "Main",
  actions: [{ op: "heal", target: { kind: "group", group: { kind: "allFriendlyUnits", maxLevel: 4 } }, amount: 2 }],
  sourceText: "【Main】All friendly Units that are Lv.4 or lower recover 2 HP.",
};

// GD01-113 The Desert Tiger — 【Main】/【Action】Choose 1 friendly (ZAFT) Unit. It gets AP+3 during this turn.
export const THE_DESERT_TIGER_MAIN: EffectSpec = {
  id: "GD01-113-Main",
  cardCode: "GD01-113",
  trigger: "Main",
  actions: [{ op: "modifyStat", target: { kind: "named", name: "target" }, stat: "ap", amount: 3, duration: "endOfTurn" }],
  targetScope: "friendlyUnit",
  targetFilter: "trait:ZAFT",
  sourceText: "【Main】/【Action】Choose 1 friendly (ZAFT) Unit. It gets AP+3 during this turn.",
};
export const THE_DESERT_TIGER_ACTION: EffectSpec = { ...THE_DESERT_TIGER_MAIN, id: "GD01-113-Action", trigger: "Action" };

// GD01-119 Iron-Fisted Discipline — 【Main】/【Action】Choose 1 enemy Unit that is Lv.4 or lower. It gets AP-2 during this turn.
export const IRON_FISTED_DISCIPLINE_MAIN: EffectSpec = {
  id: "GD01-119-Main",
  cardCode: "GD01-119",
  trigger: "Main",
  actions: [{ op: "modifyStat", target: { kind: "named", name: "target" }, stat: "ap", amount: -2, duration: "endOfTurn" }],
  targetScope: "enemyUnit",
  targetFilter: "level<=4",
  sourceText: "【Main】/【Action】Choose 1 enemy Unit that is Lv.4 or lower. It gets AP-2 during this turn.",
};
export const IRON_FISTED_DISCIPLINE_ACTION: EffectSpec = { ...IRON_FISTED_DISCIPLINE_MAIN, id: "GD01-119-Action", trigger: "Action" };

// GD01-123 Nahel Argama — 【Burst】Deploy this card. / 【Deploy】Add 1 of your Shields to your hand. Then, choose 1 enemy Unit with 3 or less HP. Rest it.
export const NAHEL_ARGAMA_BURST: EffectSpec = {
  id: "GD01-123-Burst",
  cardCode: "GD01-123",
  trigger: "Burst",
  actions: [{ op: "deployThisCard" }],
  sourceText: "【Burst】Deploy this card.",
};
export const NAHEL_ARGAMA_DEPLOY: EffectSpec = {
  id: "GD01-123-Deploy",
  cardCode: "GD01-123",
  trigger: "Deploy",
  actions: [
    { op: "addShieldToHand", player: "controller", count: 1 },
    { op: "rest", target: { kind: "named", name: "target" } },
  ],
  targetScope: "enemyUnit",
  targetFilter: "hp<=3",
  sourceText: "【Deploy】Add 1 of your Shields to your hand. Then, choose 1 enemy Unit with 3 or less HP. Rest it.",
};

// GD01-125 Zanzibar — 【Burst】Deploy this card. / 【Deploy】Add 1 of your Shields to your hand. Then, if it is your
// turn, you may deploy 1 (Zeon) Unit card that is Lv.4 or lower from your hand.
export const ZANZIBAR_BURST: EffectSpec = {
  id: "GD01-125-Burst",
  cardCode: "GD01-125",
  trigger: "Burst",
  actions: [{ op: "deployThisCard" }],
  sourceText: "【Burst】Deploy this card.",
};
export const ZANZIBAR_DEPLOY: EffectSpec = {
  id: "GD01-125-Deploy",
  cardCode: "GD01-125",
  trigger: "Deploy",
  condition: {
    predicate: "isControllersTurn",
    then: [{ op: "deployFromHandTriggered", player: "controller", filter: { cardType: "UNIT", anyTrait: ["Zeon"], maxLevel: 4 } }],
  },
  actions: [{ op: "addShieldToHand", player: "controller", count: 1 }],
  sourceText: "【Deploy】Add 1 of your Shields to your hand. Then, if it is your turn, you may deploy 1 (Zeon) Unit card that is Lv.4 or lower from your hand.",
};

// GD01-127 Gamow — 【Burst】Deploy this card. / 【Deploy】Add 1 of your Shields to your hand. /
// 【Activate･Action】Rest this Base：Choose 1 friendly (ZAFT) Unit with 5 or more AP. It gains <Breach 3> during this battle.
export const GAMOW_BURST: EffectSpec = {
  id: "GD01-127-Burst",
  cardCode: "GD01-127",
  trigger: "Burst",
  actions: [{ op: "deployThisCard" }],
  sourceText: "【Burst】Deploy this card.",
};
export const GAMOW_DEPLOY: EffectSpec = {
  id: "GD01-127-Deploy",
  cardCode: "GD01-127",
  trigger: "Deploy",
  actions: [{ op: "addShieldToHand", player: "controller", count: 1 }],
  sourceText: "【Deploy】Add 1 of your Shields to your hand.",
};
export const GAMOW_ACTIVATE_ACTION: EffectSpec = {
  id: "GD01-127-ActivateAction",
  cardCode: "GD01-127",
  trigger: "Activate·Action",
  cost: [{ op: "rest", target: { kind: "self" } }],
  actions: [{ op: "grantKeyword", target: { kind: "named", name: "target" }, keyword: "Breach 3", duration: "thisBattle" }],
  targetScope: "friendlyUnit",
  targetFilter: "trait:ZAFT;ap>=5",
  sourceText: "【Activate･Action】Rest this Base：Choose 1 friendly (ZAFT) Unit with 5 or more AP. It gains <Breach 3> during this battle.",
};

// GD01-130 13th Tactical Testing Sector — 【Burst】Deploy this card. / 【Deploy】Add 1 of your Shields to your hand. /
// 【Activate･Main】Rest this Base：If a friendly (Academy) Unit is in play, choose 1 enemy Unit. It gets AP-1 during this turn.
export const TACTICAL_TESTING_SECTOR_BURST: EffectSpec = {
  id: "GD01-130-Burst",
  cardCode: "GD01-130",
  trigger: "Burst",
  actions: [{ op: "deployThisCard" }],
  sourceText: "【Burst】Deploy this card.",
};
export const TACTICAL_TESTING_SECTOR_DEPLOY: EffectSpec = {
  id: "GD01-130-Deploy",
  cardCode: "GD01-130",
  trigger: "Deploy",
  actions: [{ op: "addShieldToHand", player: "controller", count: 1 }],
  sourceText: "【Deploy】Add 1 of your Shields to your hand.",
};
export const TACTICAL_TESTING_SECTOR_ACTIVATE_MAIN: EffectSpec = {
  id: "GD01-130-ActivateMain",
  cardCode: "GD01-130",
  trigger: "Activate·Main",
  cost: [{ op: "rest", target: { kind: "self" } }],
  condition: {
    predicate: "controllerUnitWithTraitInPlay:Academy",
    then: [{ op: "modifyStat", target: { kind: "named", name: "target" }, stat: "ap", amount: -1, duration: "endOfTurn" }],
  },
  actions: [],
  targetScope: "enemyUnit",
  sourceText: "【Activate･Main】Rest this Base：If a friendly (Academy) Unit is in play, choose 1 enemy Unit. It gets AP-1 during this turn.",
};

export const GD01_EFFECT_SPECS: EffectSpec[] = [
  GUNCANNON_WHEN_PAIRED,
  GUNTANK_DEPLOY,
  BANSHEE_UNICORN_WHEN_PAIRED,
  ZECHS_LEO_WHEN_PAIRED,
  BALL_ATTACK,
  CHUCHUS_DEMI_TRAINER_ATTACK,
  MISTRAL_DEPLOY,
  BANAGHER_LINKS_WHEN_LINKED,
  INTERCEPT_ORDERS_BURST,
  A_SHOW_OF_RESOLVE_MAIN,
  SIGNS_OF_A_REVOLUTION_BURST,
  SIGNS_OF_A_REVOLUTION_MAIN,
  FORTRESS_DEFENSE_MAIN,
  FIRST_CONTACT_BURST,
  FIRST_CONTACT_MAIN,
  BATTLE_OF_ACES_BURST,
  ZEON_REMNANT_FORCES_MAIN,
  OVERFLOWING_AFFECTION_MAIN,
  NAVAL_BOMBARDMENT_BURST,
  MIDAIR_MODIFICATIONS_MAIN,
  SIDE_7_BURST,
  SIDE_7_DEPLOY,
  SIDE_7_ACTIVATE_MAIN,
  UNDERGROUND_DESERT_BASE_BURST,
  UNDERGROUND_DESERT_BASE_DEPLOY,
  MINING_ASTEROID_PALAU_BURST,
  MINING_ASTEROID_PALAU_DEPLOY,
  GUNDAM_WHEN_PAIRED,
  ADZAM_DEPLOY,
  BLITZ_GUNDAM_DEPLOY,
  GEARA_ZULU_DEPLOY,
  GEARA_DOGA_HEAVY_ARMED_ACTIVATE_MAIN,
  GEARA_DOGA_SLEEVES_DESTROYED,
  PERFECT_STRIKE_GUNDAM_DEPLOY,
  SWORD_STRIKE_GUNDAM_ATTACK,
  DARILBALDE_DEPLOY,
  CAGALLIS_SKYGRASPER_DESTROYED,
  STEALTH_STRATAGEM_MAIN,
  STEALTH_STRATAGEM_ACTION,
  WITCH_AND_BRIDE_BURST,
  WITCH_AND_BRIDE_MAIN,
  WITCH_AND_BRIDE_ACTION,
  KUSANAGI_DEPLOY,
  NOINS_ARIES_DESTROYED,
  G_FIGHTER_DEPLOY,
  ANKSHA_DEPLOY,
  GUNDAM_SANDROCK_DEPLOY,
  SHENLONG_GUNDAM_ATTACK,
  GYAN_WHEN_PAIRED,
  SHAMBLO_ATTACK,
  GUEL_JETURK_ACTIVATE_MAIN,
  ELAN_CERES_ACTIVATE_ACTION,
  DEEP_DEVOTION_MAIN,
  DEEP_DEVOTION_ACTION,
  SECURING_THE_SUPPLY_LINE_MAIN,
  THE_DESERT_TIGER_MAIN,
  THE_DESERT_TIGER_ACTION,
  IRON_FISTED_DISCIPLINE_MAIN,
  IRON_FISTED_DISCIPLINE_ACTION,
  NAHEL_ARGAMA_BURST,
  NAHEL_ARGAMA_DEPLOY,
  ZANZIBAR_BURST,
  ZANZIBAR_DEPLOY,
  GAMOW_BURST,
  GAMOW_DEPLOY,
  GAMOW_ACTIVATE_ACTION,
  TACTICAL_TESTING_SECTOR_BURST,
  TACTICAL_TESTING_SECTOR_DEPLOY,
  TACTICAL_TESTING_SECTOR_ACTIVATE_MAIN,
  GUNDAM_PHARACT_ATTACK,
  GUNDAM_DEATHSCYTHE_WHEN_PAIRED,
  CHARS_ZAKU_II_DESTROYED,
  LAGOWE_ATTACK,
  ZEE_ZULU_ATTACK,
  JUSTICE_GUNDAM_DEPLOY,
  STRIKE_ROUGE_ACTIVATE_MAIN,
  GUNDAM_AERIAL_MIRASOUL_ACTIVATE_ACTION,
  CITIZENS_TAKE_A_STAND_MAIN,
  G_SKY_EASY_ACTIVATE_ACTION,
  WING_GUNDAM_ZERO_DEPLOY,
  BIG_ZAM_DEPLOY,
  GALLUSS_K_ACTIVATE_ACTION,
  STRATEGIC_ARMS_MAIN,
  RASIDS_ORDERS_MAIN,
  RASIDS_ORDERS_ACTION,
];

// =============================================================================
// CATÁLOGO COMPLETO GD01 (130 CARTAS)
// =============================================================================
export const GD01_CARD_DEFS: Record<string, CardDef> = {
  "GD01-001": {
    code: "GD01-001",
    nameEn: "Gundam",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["Earth Federation","White Base Team"],
    effectKeywords: ["Repair"],
    triggerKeywords: ["When Paired"],
    keywordTags: ["Repair 1"],
    link: {"kind":"pilotName","values":["Amuro Ray"]},
  },
  "GD01-002": {
    code: "GD01-002",
    nameEn: "Unicorn Gundam (Destroy Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 7,
    cost: 6,
    ap: 5,
    hp: 4,
    traits: ["Civilian"],
    triggerKeywords: ["Attack"],
    link: {"kind":"pilotName","values":["Banagher Links"]},
  },
  "GD01-003": {
    code: "GD01-003",
    nameEn: "Unicorn Gundam 02 Banshee (Destroy Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 6,
    cost: 4,
    ap: 5,
    hp: 4,
    traits: ["Earth Federation"],
    effectKeywords: ["First Strike"],
    triggerKeywords: ["Attack","During Link"],
    keywordTags: ["First Strike"],
    link: {"kind":"pilotName","values":["Marida Cruz"]},
  },
  "GD01-004": {
    code: "GD01-004",
    nameEn: "Guncannon",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 3,
    ap: 2,
    hp: 3,
    traits: ["Earth Federation","White Base Team"],
    effectKeywords: ["Repair"],
    triggerKeywords: ["When Paired"],
    keywordTags: ["Repair 1"],
    link: {"kind":"pilotName","values":["White Base Team"]},
  },
  "GD01-005": {
    code: "GD01-005",
    nameEn: "Unicorn Gundam (Unicorn Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 5,
    cost: 4,
    ap: 4,
    hp: 3,
    traits: ["Civilian"],
    triggerKeywords: ["Destroyed","During Link"],
    link: {"kind":"pilotName","values":["Banagher Links"]},
  },
  "GD01-006": {
    code: "GD01-006",
    nameEn: "Delta Plus",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Earth Federation"],
    effectKeywords: ["Repair"],
    triggerKeywords: ["During Link"],
    keywordTags: ["Repair 1"],
    link: {"kind":"pilotName","values":["Earth Federation"]},
    // 【During Link】This Unit gets HP+1. — mesmo mecanismo de ST02-010 Heero Yuy, staticAbilities já cobre.
    staticAbilities: [{ condition: "duringLink", scope: "self", stat: "hp", amount: 1 }],
  },
  "GD01-007": {
    code: "GD01-007",
    nameEn: "Noin's Aries",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 3,
    ap: 2,
    hp: 3,
    traits: ["OZ"],
    triggerKeywords: ["Destroyed"],
    link: {"kind":"pilotName","values":["Lucrezia Noin"]},
  },
  "GD01-008": {
    code: "GD01-008",
    nameEn: "Guntank",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Earth Federation","White Base Team"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-009": {
    code: "GD01-009",
    nameEn: "G-Fighter",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Earth Federation","White Base Team"],
    effectKeywords: ["High-Maneuver"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["High-Maneuver"],
    link: {"kind":"pilotName","values":["White Base Team"]},
  },
  "GD01-010": {
    code: "GD01-010",
    nameEn: "Unicorn Gundam 02 Banshee (Unicorn Mode)",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Earth Federation"],
    triggerKeywords: ["When Paired"],
    link: {"kind":"pilotName","values":["Cyber-Newtype"]},
  },
  "GD01-011": {
    code: "GD01-011",
    nameEn: "Loto",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Earth Federation"],
    link: {"kind":"pilotName","values":["Earth Federation"]},
  },
  "GD01-012": {
    code: "GD01-012",
    nameEn: "Zechs' Leo",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["OZ"],
    triggerKeywords: ["When Paired"],
    link: {"kind":"pilotName","values":["OZ"]},
  },
  "GD01-013": {
    code: "GD01-013",
    nameEn: "Gundam",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Earth Federation","White Base Team"],
    link: {"kind":"pilotName","values":["Amuro Ray"]},
  },
  "GD01-014": {
    code: "GD01-014",
    nameEn: "G-Sky Easy",
    cardType: "UNIT",
    color: "blue",
    level: 1,
    cost: 3,
    ap: 1,
    hp: 3,
    traits: ["Earth Federation","White Base Team"],
    triggerKeywords: ["During Link","Activate·Action"],
    link: {"kind":"pilotName","values":["White Base Team"]},
    oncePerTurn: true,
  },
  "GD01-015": {
    code: "GD01-015",
    nameEn: "Ball",
    cardType: "UNIT",
    color: "blue",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Earth Federation"],
    triggerKeywords: ["Attack"],
  },
  "GD01-016": {
    code: "GD01-016",
    nameEn: "Jegan",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 3,
    ap: 2,
    hp: 3,
    traits: ["Earth Federation"],
  },
  "GD01-017": {
    code: "GD01-017",
    nameEn: "Stark Jegan",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["Earth Federation"],
    effectKeywords: ["Repair"],
    keywordTags: ["Repair 1"],
    link: {"kind":"pilotName","values":["Earth Federation"]},
  },
  "GD01-018": {
    code: "GD01-018",
    nameEn: "ReZEL",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Earth Federation"],
  },
  "GD01-019": {
    code: "GD01-019",
    nameEn: "Byarlant Custom",
    cardType: "UNIT",
    color: "blue",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Earth Federation"],
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
  },
  "GD01-020": {
    code: "GD01-020",
    nameEn: "Anksha",
    cardType: "UNIT",
    color: "blue",
    level: 3,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["Earth Federation"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-021": {
    code: "GD01-021",
    nameEn: "Pisces",
    cardType: "UNIT",
    color: "blue",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["OZ"],
  },
  "GD01-022": {
    code: "GD01-022",
    nameEn: "Cancer",
    cardType: "UNIT",
    color: "blue",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["OZ"],
  },
  "GD01-023": {
    code: "GD01-023",
    nameEn: "Char's Gelgoog",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 4,
    ap: 4,
    hp: 3,
    traits: ["Zeon"],
    triggerKeywords: ["Activate·Main"],
    link: {"kind":"pilotName","values":["Char Aznable"]},
  },
  "GD01-024": {
    code: "GD01-024",
    nameEn: "Wing Gundam Zero",
    cardType: "UNIT",
    color: "green",
    level: 8,
    cost: 8,
    ap: 5,
    hp: 7,
    traits: ["G Team"],
    effectKeywords: ["High-Maneuver"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["High-Maneuver"],
    link: {"kind":"pilotName","values":["Heero Yuy"]},
  },
  "GD01-025": {
    code: "GD01-025",
    nameEn: "Gundam Deathscythe",
    cardType: "UNIT",
    color: "green",
    level: 6,
    cost: 4,
    ap: 5,
    hp: 4,
    traits: ["Operation Meteor"],
    effectKeywords: ["First Strike"],
    keywordTags: ["First Strike"],
    link: {"kind":"pilotName","values":["Duo Maxwell"]},
  },
  "GD01-026": {
    code: "GD01-026",
    nameEn: "Char's Zaku Ⅱ",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Zeon"],
    triggerKeywords: ["Destroyed","During Pair"],
    link: {"kind":"pilotName","values":["Char Aznable"]},
  },
  "GD01-027": {
    code: "GD01-027",
    nameEn: "Big Zam",
    cardType: "UNIT",
    color: "green",
    level: 7,
    cost: 5,
    ap: 5,
    hp: 6,
    traits: ["Zeon"],
    effectKeywords: ["Blocker","Breach"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["Blocker","Breach 4"],
    link: {"kind":"pilotName","values":["Dozle Zabi"]},
  },
  "GD01-028": {
    code: "GD01-028",
    nameEn: "Gundam Sandrock",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 3,
    ap: 4,
    hp: 4,
    traits: ["Operation Meteor"],
    triggerKeywords: ["Deploy"],
    link: {"kind":"pilotName","values":["Quatre Raberba Winner"]},
  },
  "GD01-029": {
    code: "GD01-029",
    nameEn: "Shenlong Gundam",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 4,
    ap: 4,
    hp: 4,
    traits: ["Operation Meteor"],
    effectKeywords: ["Blocker","Breach"],
    triggerKeywords: ["Attack"],
    keywordTags: ["Blocker","Breach 4"],
    link: {"kind":"pilotName","values":["Chang Wufei"]},
  },
  "GD01-030": {
    code: "GD01-030",
    nameEn: "Rick Dom",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Zeon"],
    effectKeywords: ["Breach"],
    keywordTags: ["Breach 2"],
  },
  "GD01-031": {
    code: "GD01-031",
    nameEn: "Gelgoog",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Zeon"],
    link: {"kind":"pilotName","values":["Zeon"]},
  },
  "GD01-032": {
    code: "GD01-032",
    nameEn: "Gyan",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Zeon"],
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["M'Quve"]},
  },
  "GD01-033": {
    code: "GD01-033",
    nameEn: "Gundam Deathscythe",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Operation Meteor"],
    effectKeywords: ["Repair"],
    keywordTags: ["Repair 1"],
    link: {"kind":"pilotName","values":["Duo Maxwell"]},
  },
  "GD01-034": {
    code: "GD01-034",
    nameEn: "Gundam Heavyarms",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Operation Meteor"],
    effectKeywords: ["Breach"],
    triggerKeywords: ["During Pair"],
    keywordTags: ["Breach 3"],
    link: {"kind":"pilotName","values":["Trowa Barton"]},
  },
  "GD01-035": {
    code: "GD01-035",
    nameEn: "Zaku Ⅱ",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 2,
    traits: ["Zeon"],
  },
  "GD01-036": {
    code: "GD01-036",
    nameEn: "Gouf",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Zeon"],
  },
  "GD01-037": {
    code: "GD01-037",
    nameEn: "Gogg",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Zeon"],
  },
  "GD01-038": {
    code: "GD01-038",
    nameEn: "Adzam",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 4,
    ap: 2,
    hp: 5,
    traits: ["Zeon"],
    triggerKeywords: ["Deploy"],
    link: {"kind":"pilotName","values":["Zeon"]},
  },
  "GD01-039": {
    code: "GD01-039",
    nameEn: "Dopp",
    cardType: "UNIT",
    color: "green",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Zeon"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-040": {
    code: "GD01-040",
    nameEn: "Wing Gundam",
    cardType: "UNIT",
    color: "green",
    level: 5,
    cost: 2,
    ap: 4,
    hp: 3,
    traits: ["Operation Meteor"],
    link: {"kind":"pilotName","values":["Heero Yuy"]},
  },
  "GD01-041": {
    code: "GD01-041",
    nameEn: "Shenlong Gundam",
    cardType: "UNIT",
    color: "green",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Operation Meteor"],
    effectKeywords: ["Breach"],
    keywordTags: ["Breach 3"],
    link: {"kind":"pilotName","values":["Chang Wufei"]},
  },
  "GD01-042": {
    code: "GD01-042",
    nameEn: "Duo's Leo",
    cardType: "UNIT",
    color: "green",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Operation Meteor"],
    link: {"kind":"pilotName","values":["Duo Maxwell"]},
    // "This Unit may choose an active enemy Unit that is Lv.2 or lower as its attack target." — mesmo campo estático de ST02-001 Wing Gundam.
    attackTargetRules: { mayTargetActiveEnemyUnit: { maxLevel: 2 } },
  },
  "GD01-043": {
    code: "GD01-043",
    nameEn: "Rasid's Maganac",
    cardType: "UNIT",
    color: "green",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Maganac Corps"],
    triggerKeywords: ["Deploy"],
    link: {"kind":"pilotName","values":["Maganac Corps"]},
  },
  "GD01-044": {
    code: "GD01-044",
    nameEn: "Kshatriya",
    cardType: "UNIT",
    color: "red",
    level: 5,
    cost: 4,
    ap: 5,
    hp: 4,
    traits: ["Neo Zeon"],
    link: {"kind":"pilotName","values":["Marida Cruz"]},
  },
  "GD01-045": {
    code: "GD01-045",
    nameEn: "Duel Gundam (Assault Shroud)",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 4,
    ap: 4,
    hp: 4,
    traits: ["ZAFT"],
    triggerKeywords: ["When Paired"],
    link: {"kind":"pilotName","values":["Yzak Jule"]},
  },
  "GD01-046": {
    code: "GD01-046",
    nameEn: "Buster Gundam",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 2,
    ap: 1,
    hp: 4,
    traits: ["ZAFT"],
    effectKeywords: ["Support"],
    triggerKeywords: ["Activate·Main"],
    keywordTags: ["Support 3","Support"],
    link: {"kind":"pilotName","values":["Dearka Elthman"]},
  },
  "GD01-047": {
    code: "GD01-047",
    nameEn: "Shamblo",
    cardType: "UNIT",
    color: "red",
    level: 8,
    cost: 7,
    ap: 6,
    hp: 5,
    traits: ["Zeon"],
    triggerKeywords: ["Attack"],
    link: {"kind":"pilotName","values":["Newtype","Cyber-Newtype"]},
  },
  "GD01-048": {
    code: "GD01-048",
    nameEn: "Zaku I Sniper Type",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 0,
    hp: 1,
    traits: ["Zeon"],
    effectKeywords: ["Support"],
    triggerKeywords: ["Deploy","Activate·Main"],
    keywordTags: ["Support 1"],
    link: {"kind":"pilotName","values":["Zeon"]},
  },
  "GD01-049": {
    code: "GD01-049",
    nameEn: "Blitz Gundam",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["ZAFT"],
    effectKeywords: ["First Strike"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["First Strike"],
    link: {"kind":"pilotName","values":["Nicol Amarfi"]},
  },
  "GD01-050": {
    code: "GD01-050",
    nameEn: "LaGOWE",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["ZAFT"],
    triggerKeywords: ["Attack"],
    link: {"kind":"pilotName","values":["ZAFT"]},
  },
  "GD01-051": {
    code: "GD01-051",
    nameEn: "Kshatriya",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Neo Zeon"],
    link: {"kind":"pilotName","values":["Cyber-Newtype"]},
  },
  "GD01-052": {
    code: "GD01-052",
    nameEn: "Geara Zulu (Guards Type)",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 3,
    ap: 2,
    hp: 4,
    traits: ["Neo Zeon"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-053": {
    code: "GD01-053",
    nameEn: "Geara Doga (Heavy Armed Type)",
    cardType: "UNIT",
    color: "red",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 2,
    traits: ["Neo Zeon"],
    triggerKeywords: ["Activate·Main"],
    oncePerTurn: true,
  },
  "GD01-054": {
    code: "GD01-054",
    nameEn: "Duel Gundam",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["ZAFT"],
    effectKeywords: ["Breach"],
    keywordTags: ["Breach 3"],
    link: {"kind":"pilotName","values":["ZAFT"]},
  },
  "GD01-055": {
    code: "GD01-055",
    nameEn: "BuCUE",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["ZAFT"],
    effectKeywords: ["Support"],
    triggerKeywords: ["Activate·Main"],
    keywordTags: ["Support 2"],
  },
  "GD01-056": {
    code: "GD01-056",
    nameEn: "Geara Doga (Sleeves)",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Neo Zeon"],
    triggerKeywords: ["Destroyed"],
  },
  "GD01-057": {
    code: "GD01-057",
    nameEn: "Dreissen (Sleeves)",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Neo Zeon"],
  },
  "GD01-058": {
    code: "GD01-058",
    nameEn: "Galluss-K",
    cardType: "UNIT",
    color: "red",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Zeon"],
    triggerKeywords: ["Activate·Action"],
    oncePerTurn: true,
  },
  "GD01-059": {
    code: "GD01-059",
    nameEn: "Zee Zulu",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Neo Zeon"],
    triggerKeywords: ["Attack"],
  },
  "GD01-060": {
    code: "GD01-060",
    nameEn: "Zaku Mariner",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 2,
    traits: ["Zeon"],
  },
  "GD01-061": {
    code: "GD01-061",
    nameEn: "ZuOOT",
    cardType: "UNIT",
    color: "red",
    level: 1,
    cost: 1,
    ap: 0,
    hp: 2,
    traits: ["ZAFT"],
    effectKeywords: ["Support"],
    triggerKeywords: ["Activate·Main"],
    keywordTags: ["Support 1"],
  },
  "GD01-062": {
    code: "GD01-062",
    nameEn: "GOOhN",
    cardType: "UNIT",
    color: "red",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["ZAFT"],
  },
  "GD01-063": {
    code: "GD01-063",
    nameEn: "ZnO",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 1,
    traits: ["ZAFT"],
    effectKeywords: ["First Strike"],
    keywordTags: ["First Strike"],
    link: {"kind":"pilotName","values":["ZAFT"]},
  },
  "GD01-064": {
    code: "GD01-064",
    nameEn: "DINN",
    cardType: "UNIT",
    color: "red",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["ZAFT"],
  },
  "GD01-065": {
    code: "GD01-065",
    nameEn: "Freedom Gundam",
    cardType: "UNIT",
    color: "white",
    level: 7,
    cost: 5,
    ap: 4,
    hp: 6,
    traits: ["Triple Ship Alliance"],
    effectKeywords: ["Blocker"],
    triggerKeywords: ["During Pair"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Kira Yamato"]},
  },
  "GD01-066": {
    code: "GD01-066",
    nameEn: "Justice Gundam",
    cardType: "UNIT",
    color: "white",
    level: 7,
    cost: 5,
    ap: 5,
    hp: 5,
    traits: ["Triple Ship Alliance"],
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Deploy","Attack","During Pair"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Athrun Zala"]},
  },
  "GD01-067": {
    code: "GD01-067",
    nameEn: "Gundam Aerial Rebuild",
    cardType: "UNIT",
    color: "white",
    level: 6,
    cost: 5,
    ap: 5,
    hp: 4,
    traits: ["Academy"],
    triggerKeywords: ["When Paired"],
    link: {"kind":"pilotName","values":["Suletta Mercury"]},
  },
  "GD01-068": {
    code: "GD01-068",
    nameEn: "Perfect Strike Gundam",
    cardType: "UNIT",
    color: "white",
    level: 5,
    cost: 3,
    ap: 4,
    hp: 4,
    traits: ["Triple Ship Alliance"],
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Deploy"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Earth Alliance"]},
  },
  "GD01-069": {
    code: "GD01-069",
    nameEn: "Strike Rouge",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 2,
    traits: ["Triple Ship Alliance"],
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Activate·Main"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Orb"]},
    oncePerTurn: true,
  },
  "GD01-070": {
    code: "GD01-070",
    nameEn: "Gundam Aerial",
    cardType: "UNIT",
    color: "white",
    level: 5,
    cost: 3,
    ap: 3,
    hp: 3,
    traits: ["Academy"],
    link: {"kind":"pilotName","values":["Suletta Mercury"]},
  },
  "GD01-071": {
    code: "GD01-071",
    nameEn: "Gundam Pharact",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Academy"],
    triggerKeywords: ["Attack","During Link"],
    link: {"kind":"pilotName","values":["Academy"]},
  },
  "GD01-072": {
    code: "GD01-072",
    nameEn: "Launcher Strike Gundam",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 3,
    hp: 4,
    traits: ["Earth Alliance"],
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
    link: {"kind":"pilotName","values":["Earth Alliance"]},
  },
  "GD01-073": {
    code: "GD01-073",
    nameEn: "Sword Strike Gundam",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Earth Alliance"],
    triggerKeywords: ["Attack","During Link"],
    link: {"kind":"pilotName","values":["Earth Alliance"]},
  },
  "GD01-074": {
    code: "GD01-074",
    nameEn: "Chuchu's Demi Trainer",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 3,
    hp: 1,
    traits: ["Academy"],
    triggerKeywords: ["Attack"],
    link: {"kind":"pilotName","values":["Chuatury Panlunch"]},
  },
  "GD01-075": {
    code: "GD01-075",
    nameEn: "Darilbalde",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 4,
    hp: 2,
    traits: ["Academy"],
    triggerKeywords: ["Deploy"],
    link: {"kind":"pilotName","values":["Academy"]},
  },
  "GD01-076": {
    code: "GD01-076",
    nameEn: "Michaelis",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 3,
    hp: 3,
    traits: ["Academy"],
    link: {"kind":"pilotName","values":["Academy"]},
  },
  "GD01-077": {
    code: "GD01-077",
    nameEn: "Strike Gundam",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 2,
    ap: 3,
    hp: 4,
    traits: ["Earth Alliance"],
    link: {"kind":"pilotName","values":["Kira Yamato"]},
  },
  "GD01-078": {
    code: "GD01-078",
    nameEn: "Mistral",
    cardType: "UNIT",
    color: "white",
    level: 1,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Earth Alliance"],
    triggerKeywords: ["Deploy"],
  },
  "GD01-079": {
    code: "GD01-079",
    nameEn: "Skygrasper",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Earth Alliance"],
    link: {"kind":"pilotName","values":["Earth Alliance"]},
  },
  "GD01-080": {
    code: "GD01-080",
    nameEn: "Cagalli's Skygrasper",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 1,
    traits: ["Earth Alliance"],
    triggerKeywords: ["Destroyed"],
    link: {"kind":"pilotName","values":["Cagalli Yula Athha"]},
  },
  "GD01-081": {
    code: "GD01-081",
    nameEn: "M1 Astray",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Triple Ship Alliance"],
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
  },
  "GD01-082": {
    code: "GD01-082",
    nameEn: "Gundam Aerial (Mirasoul Flight Unit)",
    cardType: "UNIT",
    color: "white",
    level: 4,
    cost: 3,
    ap: 4,
    hp: 3,
    traits: ["Academy"],
    triggerKeywords: ["During Pair","Activate·Action"],
    link: {"kind":"pilotName","values":["Suletta Mercury"]},
    oncePerTurn: true,
  },
  "GD01-083": {
    code: "GD01-083",
    nameEn: "Guel's Dilanza",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 2,
    traits: ["Academy"],
    link: {"kind":"pilotName","values":["Academy"]},
  },
  "GD01-084": {
    code: "GD01-084",
    nameEn: "Beguir-Pente",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 2,
    ap: 2,
    hp: 3,
    traits: ["Academy"],
  },
  "GD01-085": {
    code: "GD01-085",
    nameEn: "Demi Garrison",
    cardType: "UNIT",
    color: "white",
    level: 2,
    cost: 1,
    ap: 2,
    hp: 2,
    traits: ["Academy"],
  },
  "GD01-086": {
    code: "GD01-086",
    nameEn: "Gundam Lfrith",
    cardType: "UNIT",
    color: "white",
    level: 3,
    cost: 2,
    ap: 2,
    hp: 4,
    traits: ["Vanadis Institute"],
    effectKeywords: ["Blocker"],
    keywordTags: ["Blocker"],
  },
  "GD01-087": {
    code: "GD01-087",
    nameEn: "Sayla Mass",
    cardType: "PILOT",
    color: "blue",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Earth Federation","White Base Team","Newtype"],
    effectKeywords: ["Repair"],
    triggerKeywords: ["Burst"],
    keywordTags: ["Repair 1"],
    hasBurst: true,
  },
  "GD01-088": {
    code: "GD01-088",
    nameEn: "Banagher Links",
    cardType: "PILOT",
    color: "blue",
    level: 5,
    cost: 1,
    ap: 2,
    hp: 2,
    traits: ["Civilian","Newtype"],
    triggerKeywords: ["When Linked","Burst"],
    hasBurst: true,
  },
  "GD01-089": {
    code: "GD01-089",
    nameEn: "Riddhe Marcenas",
    cardType: "PILOT",
    color: "blue",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Earth Federation"],
    effectKeywords: ["Repair"],
    triggerKeywords: ["Burst"],
    keywordTags: ["Repair"],
    hasBurst: true,
  },
  "GD01-090": {
    code: "GD01-090",
    nameEn: "Duo Maxwell",
    cardType: "PILOT",
    color: "green",
    level: 4,
    cost: 1,
    ap: 1,
    hp: 2,
    traits: ["Operation Meteor"],
    triggerKeywords: ["During Link","Burst"],
    hasBurst: true,
  },
  "GD01-091": {
    code: "GD01-091",
    nameEn: "Chang Wufei",
    cardType: "PILOT",
    color: "green",
    level: 4,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Operation Meteor"],
    effectKeywords: ["Breach"],
    triggerKeywords: ["Burst"],
    keywordTags: ["Breach"],
    hasBurst: true,
  },
  "GD01-092": {
    code: "GD01-092",
    nameEn: "M'Quve",
    cardType: "PILOT",
    color: "green",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Zeon"],
    effectKeywords: ["Breach"],
    triggerKeywords: ["Burst"],
    keywordTags: ["Breach 1"],
    hasBurst: true,
  },
  "GD01-093": {
    code: "GD01-093",
    nameEn: "Marida Cruz",
    cardType: "PILOT",
    color: "red",
    level: 4,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Neo Zeon","Cyber-Newtype"],
    triggerKeywords: ["Attack","During Link","Burst"],
    hasBurst: true,
  },
  "GD01-094": {
    code: "GD01-094",
    nameEn: "Yzak Jule",
    cardType: "PILOT",
    color: "red",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["ZAFT","Coordinator"],
    triggerKeywords: ["Burst"],
    hasBurst: true,
  },
  "GD01-095": {
    code: "GD01-095",
    nameEn: "Dearka Elthman",
    cardType: "PILOT",
    color: "red",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["ZAFT","Coordinator"],
    triggerKeywords: ["When Linked","Burst"],
    hasBurst: true,
  },
  "GD01-096": {
    code: "GD01-096",
    nameEn: "Cagalli Yula Athha",
    cardType: "PILOT",
    color: "white",
    level: 4,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Orb"],
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Burst"],
    keywordTags: ["Blocker"],
    hasBurst: true,
  },
  "GD01-097": {
    code: "GD01-097",
    nameEn: "Guel Jeturk",
    cardType: "PILOT",
    color: "white",
    level: 3,
    cost: 1,
    ap: 1,
    hp: 1,
    traits: ["Academy"],
    triggerKeywords: ["Activate·Main","Burst"],
    hasBurst: true,
    oncePerTurn: true,
  },
  "GD01-098": {
    code: "GD01-098",
    nameEn: "Elan Ceres (Enhanced Person Number 4)",
    cardType: "PILOT",
    color: "white",
    level: 4,
    cost: 1,
    ap: 2,
    hp: 1,
    traits: ["Academy"],
    triggerKeywords: ["Activate·Action","Burst"],
    hasBurst: true,
    oncePerTurn: true,
  },
  "GD01-099": {
    code: "GD01-099",
    nameEn: "Intercept Orders",
    cardType: "COMMAND",
    color: "blue",
    level: 4,
    cost: 2,
    triggerKeywords: ["Main","Action","Burst"],
    hasBurst: true,
  },
  "GD01-100": {
    code: "GD01-100",
    nameEn: "A Show of Resolve",
    cardType: "COMMAND",
    color: "blue",
    level: 4,
    cost: 3,
    triggerKeywords: ["Main"],
  },
  "GD01-101": {
    code: "GD01-101",
    nameEn: "Deep Devotion",
    cardType: "COMMAND",
    color: "blue",
    level: 2,
    cost: 1,
    traits: ["OZ"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-102": {
    code: "GD01-102",
    nameEn: "Securing the Supply Line",
    cardType: "COMMAND",
    color: "blue",
    level: 4,
    cost: 2,
    triggerKeywords: ["Main"],
  },
  "GD01-103": {
    code: "GD01-103",
    nameEn: "The Stubborn Cog",
    cardType: "COMMAND",
    color: "blue",
    level: 1,
    cost: 1,
    traits: ["Earth Federation"],
    triggerKeywords: ["Main"],
  },
  "GD01-104": {
    code: "GD01-104",
    nameEn: "Signs of a Revolution",
    cardType: "COMMAND",
    color: "blue",
    level: 3,
    cost: 2,
    triggerKeywords: ["Main","Burst"],
    hasBurst: true,
  },
  "GD01-105": {
    code: "GD01-105",
    nameEn: "Citizens, Take a Stand!",
    cardType: "COMMAND",
    color: "green",
    level: 4,
    cost: 1,
    triggerKeywords: ["Main","Burst"],
    hasBurst: true,
  },
  "GD01-106": {
    code: "GD01-106",
    nameEn: "Fortress Defense",
    cardType: "COMMAND",
    color: "green",
    level: 5,
    cost: 2,
    traits: ["Zeon"],
    triggerKeywords: ["Main"],
  },
  "GD01-107": {
    code: "GD01-107",
    nameEn: "First Contact",
    cardType: "COMMAND",
    color: "green",
    level: 3,
    cost: 3,
    triggerKeywords: ["Main","Burst"],
    hasBurst: true,
  },
  "GD01-108": {
    code: "GD01-108",
    nameEn: "Strategic Arms",
    cardType: "COMMAND",
    color: "green",
    level: 6,
    cost: 6,
    // "Blocker" no texto oficial é o FILTRO do alvo ("all Units with <Blocker>"),
    // não uma keyword da própria carta — Fase 1 (Gemini) tinha marcado errado
    // como effectKeywords/keywordTags do Command. Corrigido ao autorar o
    // EffectSpec (STRATEGIC_ARMS_MAIN).
    triggerKeywords: ["Main"],
  },
  "GD01-109": {
    code: "GD01-109",
    nameEn: "The Path to Victory or Defeat",
    cardType: "COMMAND",
    color: "green",
    level: 5,
    cost: 1,
    triggerKeywords: ["Main"],
  },
  "GD01-110": {
    code: "GD01-110",
    nameEn: "Rasid's Orders",
    cardType: "COMMAND",
    color: "green",
    level: 3,
    cost: 1,
    traits: ["Maganac Corps"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-111": {
    code: "GD01-111",
    nameEn: "Battle of Aces",
    cardType: "COMMAND",
    color: "red",
    level: 3,
    cost: 2,
    triggerKeywords: ["Main","Action","Burst"],
    hasBurst: true,
  },
  "GD01-112": {
    code: "GD01-112",
    nameEn: "Extreme Hatred",
    cardType: "COMMAND",
    color: "red",
    level: 6,
    cost: 1,
    traits: ["Zeon","Newtype"],
    triggerKeywords: ["Main"],
  },
  "GD01-113": {
    code: "GD01-113",
    nameEn: "The Desert Tiger",
    cardType: "COMMAND",
    color: "red",
    level: 3,
    cost: 1,
    traits: ["ZAFT","Coordinator"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-114": {
    code: "GD01-114",
    nameEn: "Assault on Torrington Base",
    cardType: "COMMAND",
    color: "red",
    level: 1,
    cost: 1,
    traits: ["Zeon"],
    triggerKeywords: ["Action"],
  },
  "GD01-115": {
    code: "GD01-115",
    nameEn: "Zeon Remnant Forces",
    cardType: "COMMAND",
    color: "red",
    level: 2,
    cost: 1,
    triggerKeywords: ["Main","Action"],
  },
  "GD01-116": {
    code: "GD01-116",
    nameEn: "Stealth Stratagem",
    cardType: "COMMAND",
    color: "red",
    level: 2,
    cost: 1,
    traits: ["ZAFT","Coordinator"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-117": {
    code: "GD01-117",
    nameEn: "The Witch and the Bride",
    cardType: "COMMAND",
    color: "white",
    level: 5,
    cost: 2,
    triggerKeywords: ["Main","Action","Burst"],
    hasBurst: true,
  },
  "GD01-118": {
    code: "GD01-118",
    nameEn: "Overflowing Affection",
    cardType: "COMMAND",
    color: "white",
    level: 2,
    cost: 1,
    triggerKeywords: ["Main"],
  },
  "GD01-119": {
    code: "GD01-119",
    nameEn: "Iron-Fisted Discipline",
    cardType: "COMMAND",
    color: "white",
    level: 2,
    cost: 1,
    traits: ["Academy"],
    triggerKeywords: ["Main","Action"],
  },
  "GD01-120": {
    code: "GD01-120",
    nameEn: "Naval Bombardment",
    cardType: "COMMAND",
    color: "white",
    level: 2,
    cost: 1,
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Action","Burst"],
    keywordTags: ["Blocker"],
    hasBurst: true,
  },
  "GD01-121": {
    code: "GD01-121",
    nameEn: "Midair Modifications",
    cardType: "COMMAND",
    color: "white",
    level: 3,
    cost: 2,
    effectKeywords: ["Blocker"],
    triggerKeywords: ["Main","Burst"],
    keywordTags: ["Blocker"],
    hasBurst: true,
  },
  "GD01-122": {
    code: "GD01-122",
    nameEn: "Covert Operative",
    cardType: "COMMAND",
    color: "white",
    level: 3,
    cost: 1,
    traits: ["Academy"],
    triggerKeywords: ["Main"],
  },
  "GD01-123": {
    code: "GD01-123",
    nameEn: "Nahel Argama",
    cardType: "BASE",
    color: "blue",
    level: 3,
    cost: 2,
    ap: 0,
    hp: 5,
    traits: ["Earth Federation","Warship"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-124": {
    code: "GD01-124",
    nameEn: "Side 7",
    cardType: "BASE",
    color: "blue",
    level: 1,
    cost: 1,
    ap: 0,
    hp: 4,
    traits: ["Earth Federation","Stronghold"],
    triggerKeywords: ["Deploy","Activate·Main","Burst"],
    hasBurst: true,
  },
  "GD01-125": {
    code: "GD01-125",
    nameEn: "Zanzibar",
    cardType: "BASE",
    color: "green",
    level: 4,
    cost: 2,
    ap: 0,
    hp: 5,
    traits: ["Zeon","Warship"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-126": {
    code: "GD01-126",
    nameEn: "Underground Desert Base",
    cardType: "BASE",
    color: "green",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 6,
    traits: ["Maganac Corps","Stronghold"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-127": {
    code: "GD01-127",
    nameEn: "Gamow",
    cardType: "BASE",
    color: "red",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 5,
    traits: ["ZAFT","Warship"],
    // "Breach 3" NÃO é keyword estática do próprio Gamow (Base, AP0, não ataca) —
    // é concedida a uma Unit escolhida via 【Activate･Action】 (GAMOW_ACTIVATE_ACTION).
    triggerKeywords: ["Deploy","Activate·Action","Burst"],
    hasBurst: true,
  },
  "GD01-128": {
    code: "GD01-128",
    nameEn: "Mining Asteroid Palau",
    cardType: "BASE",
    color: "red",
    level: 2,
    cost: 1,
    ap: 0,
    hp: 6,
    traits: ["Neo Zeon","Stronghold"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-129": {
    code: "GD01-129",
    nameEn: "Kusanagi",
    cardType: "BASE",
    color: "white",
    level: 4,
    cost: 2,
    ap: 0,
    hp: 4,
    traits: ["Triple Ship Alliance","Warship"],
    triggerKeywords: ["Deploy","Burst"],
    hasBurst: true,
  },
  "GD01-130": {
    code: "GD01-130",
    nameEn: "13th Tactical Testing Sector",
    cardType: "BASE",
    color: "white",
    level: 3,
    cost: 1,
    ap: 0,
    hp: 5,
    traits: ["Academy","Stronghold"],
    triggerKeywords: ["Deploy","Activate·Main","Burst"],
    hasBurst: true,
  },
};
