ALTER TABLE "CardSet" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "CardSet" ADD COLUMN "deletedAt" TIMESTAMP(3);

ALTER TABLE "TaxonomyEntry" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TaxonomyEntry" ADD COLUMN "deletedAt" TIMESTAMP(3);

ALTER TABLE "Card" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Card" ADD COLUMN "deletedAt" TIMESTAMP(3);

ALTER TABLE "Ruling" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Ruling" ADD COLUMN "deletedAt" TIMESTAMP(3);

ALTER TABLE "Tournament" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tournament" ADD COLUMN "deletedAt" TIMESTAMP(3);
